### PR TITLE
fix: Change Estimator.logs() to use latest_training_job.name

### PR DESCRIPTION
**Pull request by philschmid**
If you call any `Estimator.logs()` either `Pytorch` you will receive the following error

```python
ParamValidationError: Parameter validation failed:
Invalid type for parameter TrainingJobName, value: <sagemaker.estimator._TrainingJob object at 0x7ffc4af0d520>, type: <class 'sagemaker.estimator._TrainingJob'>, valid types: <class 'str'>
```

adjusted it to `self.latest_training_job.name` and it works

*Description of changes: Fixes printing logs of Estimator*

*Testing done: yes*

#### General

- [ x] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [ ] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [ ] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [ ] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [ ] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ahsan-z-khan** [comment]
black-check is failing. Please check formatting. 

ERROR:   black-check: parallel child exit code 1

**Comment by philschmid** [comment]
@ahsan-z-khan do you have more information for me? I ran the `tox -e black-check` locally and it didn´t fail. Sadly i cannot take a look at the Build details

image

**Comment by ahsan-z-khan** [comment]
@philschmid I retried the build couple of times. Currently showing this error. 
Screen Shot 2021-01-05 at 10 54 14 AM

**Comment by ahsan-z-khan** [comment]
@philschmid I think you need to update the unit test. 
Screen Shot 2021-01-05 at 12 48 24 PM

**Review by ChoiByungWook — APPROVED** [review]
AWESOME!!!

**Pull request merged**
