### PR TITLE
Update async_inference_response.py

### PR DESCRIPTION
**Pull request by gautam1858**
1. Add docstrings to the methods.

2. Add docstrings to the get_result(), _get_result_from_s3(), _get_result_from_s3_output_path(), and _get_result_from_s3_output_failure_paths() methods to explain what they do and how to use them. Break up the _get_result_from_s3() method into smaller functions.

3. Break up the _get_result_from_s3() method into two smaller functions, _get_result_from_s3_output_path() and _get_result_from_s3_output_failure_paths(). Add unit tests.

4. Add unit tests for the AsyncInferenceResponse class to ensure that the code is working as expected.

### CODE REVIEW

**Review by mihaimaruseac — CHANGES_REQUESTED** [review]
No dcostrings added, the changes only add whitespace

**Comment by mihaimaruseac** [comment]
This looks like another spam PR (author has already sent 3 such PRs to TensorFlow and 3 to Keras and 1 to deepmind).

**Comment by mufaddal-rohawala** [comment]
@gautam1858 none of the changes in description match the changes in this PR. Whats the status on this PR?

**Comment by mufaddal-rohawala** [comment]
@gautam1858 Im closing this PR, please reopen a new PR as applicable.

**Pull request closed without merging**
