### PR TITLE
feature: Add transformers 4.32.0 - PyTorch 2.0.0

### PR DESCRIPTION
**Pull request by oleksiishevchuk**
*Issue [#4075](https://github.com/aws/sagemaker-python-sdk/issues/4075), if available:*

*Description of changes:*
Update Image URI for:
Transformers 4.32 - PyTorch 2.0 Inference DLC
Transformers 4.32 - PyTorch 2.0 Training DLC

*Testing done:*

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [ ] I certify that the changes I am introducing will be backward compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [ ] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [ ] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added unit and/or integration tests as appropriate to ensure backward compatibility of the changes
- [ ] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [ ] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by oleksiishevchuk** [comment]
Hi. Can somebody please run tests?

**Review by knikure — COMMENTED** [review]
/bot run all

**Comment by oleksiishevchuk** [comment]
Same failure as in https://github.com/aws/sagemaker-python-sdk/pull/3904#issuecomment-1595181446

`sagemaker.exceptions.UnexpectedStatusException: Error for Training job huggingface-pytorch-training-2023-08-28-20-14-36-905: Failed. Reason: ClientError: Data download failed:API error (404): manifest for 763104351884.dkr.ecr.us-west-2.amazonaws.com/huggingface-pytorch-training:2.0.0-transformers4.32.0-gpu-py310-cu118-ubuntu20.04 not found: manifest unknown: Requested image not found`

Needs an update about image availability - https://github.com/aws/sagemaker-python-sdk/pull/3904#issuecomment-1678075674

**Review by mufaddal-rohawala — COMMENTED** [review]
/bot run pr

**Review by mufaddal-rohawala — APPROVED** [review]

**Comment by mufaddal-rohawala** [comment]
Need to fix the issues associated with 
```
E           sagemaker.exceptions.UnexpectedStatusException: Error for Training job huggingface-pytorch-training-2023-08-31-21-12-47-618: Failed. Reason: ClientError: TrainingHostAgent Initialization failed:API error (404): manifest for 763104351884.dkr.ecr.us-west-2.amazonaws.com/huggingface-pytorch-training:2.0.0-transformers4.32.0-gpu-py310-cu118-ubuntu20.04 not found: manifest unknown: Requested image not found

```

**Comment by mufaddal-rohawala** [comment]
Only sagemaker-python-sdk-pr tests is yet to be validated for this PR.

**Comment by oleksiishevchuk** [comment]
Thanks @mufaddal-rohawala , please see my comment above about this issue https://github.com/aws/sagemaker-python-sdk/pull/4076#issuecomment-1697094893

**Review by benieric — COMMENTED** [review]
/bot run all

**Comment by knikure** [comment]
@oleksiishevchuk Please open this issue with DLC who is an upstream dependency to release these images and then we can rework on this PR. Meanwhile I advice you to use latest PyTorch which comes with transformers 4.36.0

**Pull request closed without merging**
