### PR TITLE
feature: Add Extra Parameters to Lambda Function Wrapper

### PR DESCRIPTION
**Pull request by dipanjank**
*Issue #3563 

*Description of changes:*

* Add ``VpcConfig``, ``Architectures``, ``Environment`` and ``Layers`` parameters for boto3 Lambda ``create_function`` call.
* Add ``Architectures`` for  boto3 Lambda  ``update_function`` call.

*Testing done:*

```shell
pytest -vs tests/unit/test_lambda_helper.py
================================================================================================= test session starts ==================================================================================================
platform darwin -- Python 3.7.11, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 -- /Users/dipanjan.kailthya@TMNL.nl/PycharmProjects/sagemaker-python-sdk-personal/venv/bin/python3
cachedir: .pytest_cache
rootdir: /Users/dipanjan.kailthya@TMNL.nl/PycharmProjects/sagemaker-python-sdk-personal, configfile: tox.ini
plugins: forked-1.4.0, timeout-2.1.0, rerunfailures-10.2, xdist-2.4.0, anyio-3.6.2, cov-3.0.0
collected 28 items                                                                                                                                                                                                     

tests/unit/test_lambda_helper.py::test_lambda_object_with_arn_happycase PASSED
tests/unit/test_lambda_helper.py::test_lambda_object_with_name_happycase1 PASSED
tests/unit/test_lambda_helper.py::test_lambda_object_with_name_happycase2 PASSED
tests/unit/test_lambda_helper.py::test_lambda_object_with_no_name_and_arn_error PASSED
tests/unit/test_lambda_helper.py::test_lambda_object_no_code_error PASSED
tests/unit/test_lambda_helper.py::test_lambda_object_both_script_and_code_dir_error_with_name PASSED
tests/unit/test_lambda_helper.py::test_lambda_object_both_script_and_code_dir_error_with_arn PASSED
tests/unit/test_lambda_helper.py::test_lambda_object_no_handler_error PASSED
tests/unit/test_lambda_helper.py::test_lambda_object_no_execution_role_error PASSED
tests/unit/test_lambda_helper.py::test_create_lambda_happycase1 PASSED
tests/unit/test_lambda_helper.py::test_create_lambda_happycase2 PASSED
tests/unit/test_lambda_helper.py::test_create_lambda_happycase3 PASSED
tests/unit/test_lambda_helper.py::test_create_lambda_no_function_name_error PASSED
tests/unit/test_lambda_helper.py::test_create_lambda_client_error PASSED
tests/unit/test_lambda_helper.py::test_update_lambda_happycase1 PASSED
tests/unit/test_lambda_helper.py::test_update_lambda_happycase2 PASSED
tests/unit/test_lambda_helper.py::test_update_lambda_happycase3 PASSED
tests/unit/test_lambda_helper.py::test_update_lambda_s3bucket_not_provided PASSED
tests/unit/test_lambda_helper.py::test_update_lambda_client_error PASSED
tests/unit/test_lambda_helper.py::test_upsert_lambda_happycase1 PASSED
tests/unit/test_lambda_helper.py::test_upsert_lambda_happycase2 PASSED
tests/unit/test_lambda_helper.py::test_upsert_lambda_client_error PASSED
tests/unit/test_lambda_helper.py::test_invoke_lambda_happycase PASSED
tests/unit/test_lambda_helper.py::test_invoke_lambda_client_error PASSED
tests/unit/test_lambda_helper.py::test_delete_lambda_happycase PASSED
tests/unit/test_lambda_helper.py::test_delete_lambda_client_error PASSED
tests/unit/test_lambda_helper.py::test_upload_to_s3 PASSED
tests/unit/test_lambda_helper.py::test_zip_lambda_code PASSED

```

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [X] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [X] I certify that the changes I am introducing will be backward compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [X] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [X] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [X] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [X] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [X] I have added unit and/or integration tests as appropriate to ensure backward compatibility of the changes
- [X] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [X] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jpcpereira** [comment]
Hi @dipanjank , nice PR, would be really great if you could include "Layers" to the additional inputs to create the Lambda function. This is also one of the options in Boto3. Would enable setting AWS Lambda Layers with extra useful libraries without having to zip & pass them.

**Comment by dipanjank** [comment]
> Hi @dipanjank , nice PR, would be really great if you could include "Layers" to the additional inputs to create the Lambda function. This is also one of the options in Boto3. Would enable setting AWS Lambda Layers with extra useful libraries without having to zip & pass them.

Thanks for the review! sure.

**Review by knikure — COMMENTED** [review]
/bot run all

**Review by knikure — COMMENTED** [review]
@dipanjank Can you resolve the conflicts in your branch and rebase it over master?

**Comment by dipanjank** [comment]
@knikure  sure, will do!

**Comment by dipanjank** [comment]
Hi @knikure updated with latest from master + added the "layer" argument requested by @jpcpereira. Can you please review again?

**Review by knikure — APPROVED** [review]
/bot run all

**Review by knikure — COMMENTED** [review]
/bot run all

**Review by knikure — COMMENTED** [review]
/bot run all

**Pull request merged**
