### PR TITLE
feat: Add transformers 4.29 - PyTorch 2.0.0 training and inference

### PR DESCRIPTION
**Pull request by phall1**
*Issue #, if available:* #3896

*Description of changes:*
Update Image URI for:

Transformers 4.29 - PyTorch 2.0 Inference DLC
Transformers 4.29 - PyTorch 2.0 Training DLC

*Testing done:*

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [ ] I certify that the changes I am introducing will be backward compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [ ] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [ ] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [ ] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added unit and/or integration tests as appropriate to ensure backward compatibility of the changes
- [ ] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [ ] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by knikure — COMMENTED** [review]
/bot run all

**Comment by phall1** [comment]
Updated python version for torch 2.0 compatibility per the failed tests in the failed builds

**Comment by phall1** [comment]
Looks like the image isn't available yet, per here:

https://github.com/aws/deep-learning-containers/blob/master/available_images.md

Do we know if this is being worked on or how I could contribute to getting this image available?
Error from logs:
```
sagemaker.exceptions.UnexpectedStatusException: Error for Processing job test-huggingface-2023-06-07-04-47-23-957: Failed. Reason: ClientError: API error (404): manifest for 763104351884.dkr.ecr.us-west-2.amazonaws.com/huggingface-pytorch-training:2.0.0-transformers4.29.0-gpu-py310-cu118-ubuntu20.04 not found: manifest unknown: Requested image not found
```

**Review by mufaddal-rohawala — COMMENTED** [review]
/bot run all

**Review by knikure — COMMENTED** [review]
/bot run all

**Comment by phall1** [comment]
> Looks like the image isn't available yet, per here:
> 
> 
> 
> https://github.com/aws/deep-learning-containers/blob/master/available_images.md
> 
> 
> 
> Do we know if this is being worked on or how I could contribute to getting this image available?
> 
> Error from logs:
> 
> ```
> 
> sagemaker.exceptions.UnexpectedStatusException: Error for Processing job test-huggingface-2023-06-07-04-47-23-957: Failed. Reason: ClientError: API error (404): manifest for 763104351884.dkr.ecr.us-west-2.amazonaws.com/huggingface-pytorch-training:2.0.0-transformers4.29.0-gpu-py310-cu118-ubuntu20.04 not found: manifest unknown: Requested image not found
> 
> ```

Same error as before - bumping my question l

**Comment by knikure** [comment]
> > Looks like the image isn't available yet, per here:
> > [aws/deep-learning-containers@`master`/available_images.md](https://github.com/aws/deep-learning-containers/blob/master/available_images.md?rgh-link-date=2023-06-16T19%3A22%3A00Z)
> > Do we know if this is being worked on or how I could contribute to getting this image available?
> > Error from logs:
> > ```
> > 
> > sagemaker.exceptions.UnexpectedStatusException: Error for Processing job test-huggingface-2023-06-07-04-47-23-957: Failed. Reason: ClientError: API error (404): manifest for 763104351884.dkr.ecr.us-west-2.amazonaws.com/huggingface-pytorch-training:2.0.0-transformers4.29.0-gpu-py310-cu118-ubuntu20.04 not found: manifest unknown: Requested image not found
> > ```
> 
> Same error as before - bumping my question l

We will have to check with DLC team to verify on the image availability.
@ShiboXing Can you help answer this question?

**Comment by knikure** [comment]
@phall1 Can you check with someone in DLC if transformers 4.29 is supported with PT 2.0. If not, can we close this PR?

**Comment by oleksiishevchuk** [comment]
It would be great to get some feedback about this, as we would like to add support for further transformers version (e.g. https://github.com/aws/sagemaker-python-sdk/pull/4076)

**Review by mufaddal-rohawala — COMMENTED** [review]
/bot run all

**Comment by oleksiishevchuk** [comment]
Hi @knikure, seems like the same issue with not available image still exists. Do you have any suggestions how to get feedback from the DLC team (@phall1 @ShiboXing) or if we can somehow contribute to help to resolve it?

**Comment by knikure** [comment]
> Hi @knikure, seems like the same issue with not available image still exists. Do you have any suggestions how to get feedback from the DLC team (@phall1 @ShiboXing) or if we can somehow contribute to help to resolve it?

@oleksiishevchuk It would be better to always take a look at what DLC has already released for [training](https://github.com/aws/deep-learning-containers/blob/master/available_images.md#huggingface-training-containers) and [inference](https://github.com/aws/deep-learning-containers/blob/master/available_images.md#huggingface-inference-containers) and raise issues like #3896 with [DLC](https://github.com/aws/deep-learning-containers) to make them cater to these requests. PySDK is downstream and cannot help release these images.

**Comment by knikure** [comment]
Closing this PR as we are tracking this as a feature request.

**Pull request closed without merging**
