### PR TITLE
feature: sts endpoint support

### PR DESCRIPTION
**Pull request by jmgray24**
*Issue #, if available:* N/A

*Description of changes:*

Added the ability to pass an optional STS endpoint URL. This optional STS url allows the override of the global endpoint for regional ones.

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

- [x] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#commit-message-guidlines)
- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have updated any necessary [documentation](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jesterhazy** [comment]
### AWS CodeBuild CI Report

* Result: FAILED
* [Build Logs](https://9dzx6wxcy9.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=16b18e42-9f84-40d1-84ba-c98759987c84%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by jesterhazy** [comment]
### AWS CodeBuild CI Report

* Result: FAILED
* [Build Logs](https://9dzx6wxcy9.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=5203f781-258f-4bf9-a8b7-e5dfbcad5916%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by jesterhazy** [comment]
### AWS CodeBuild CI Report

* Result: FAILED
* [Build Logs](https://9dzx6wxcy9.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=7e7cc454-e27c-4ca2-b0f5-b7c2f5cb4f4b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by jesterhazy** [comment]
### AWS CodeBuild CI Report

* Result: FAILED
* [Build Logs](https://9dzx6wxcy9.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=be7d98c5-3546-45f7-9b72-a8d6e6e4ddd5%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by jesterhazy** [comment]
### AWS CodeBuild CI Report

* Result: FAILED
* [Build Logs](https://9dzx6wxcy9.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=38e78e1f-f78f-400f-bf26-467f750445a7%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by jmgray24** [comment]
This appears to be a issue with the build outside of the scope of the changes in this PR as it is also seen in https://github.com/aws/sagemaker-python-sdk/pull/786.

Thus ready for review.

**Comment by jesterhazy** [comment]
### AWS CodeBuild CI Report

* Result: FAILED
* [Build Logs](https://9dzx6wxcy9.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=90971775-9809-4190-a61e-414b8f32ed68%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by imujjwal96** [comment]
The issue has been fixed in the PR #776
you may run the following commands to pull the latest commits:

    git remote add upstream https://github.com/aws/sagemaker-python-sdk.git
    git pull --rebase upstream master
    git push origin master

**Comment by jesterhazy** [comment]
### AWS CodeBuild CI Report

* Result: FAILED
* [Build Logs](https://9dzx6wxcy9.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=4672405b-0549-4e1a-b1d2-90662737c722%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by jmgray24** [comment]
Failure of test here 

_________________________ test_horovod_local_mode[2-2] _________________________
[gw9] linux -- Python 3.6.7 /codebuild/output/src402338386/src/github.com/aws/sagemaker-python-sdk/.tox/py36/bin/python
sagemaker_local_session = <sagemaker.local.local_session.LocalSession object at 0x7fda65dae748>
instances = 2, processes = 2
tmpdir = local('/tmp/pytest-of-root/pytest-2/popen-gw9/test_horovod_local_mode_2_2_0')

    @pytest.mark.local_mode
    @pytest.mark.parametrize('instances, processes', [
        [1, 2],
        (2, 1),
        (2, 2)])
    def test_horovod_local_mode(sagemaker_local_session, instances, processes, tmpdir):
        output_path = 'file://%s' % tmpdir
        job_name = sagemaker.utils.unique_name_from_base('tf-horovod')
        estimator = TensorFlow(entry_point=os.path.join(horovod_dir, 'test_hvd_basic.py'),
                               role='SageMakerRole',
                               train_instance_count=2,
                               train_instance_type='local',
                               sagemaker_session=sagemaker_local_session,
                               py_version=integ.PYTHON_VERSION,
                               script_mode=True,
                               output_path=output_path,
                               framework_version='1.12',
                               distributions={'mpi': {'enabled': True,
                                                      'processes_per_host': processes}})

        with timeout.timeout(minutes=integ.TRAINING_DEFAULT_TIMEOUT_MINUTES):
            estimator.fit(job_name=job_name)

            tmp = str(tmpdir)
            extract_files(output_path.replace('file://', ''), tmp)

            size = instances * processes

            for rank in range(size):
>               assert read_json('rank-%s' % rank, tmp)['rank'] == rank

tests/integ/test_horovod.py:93:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

file = 'rank-0'
tmp = '/tmp/pytest-of-root/pytest-2/popen-gw9/test_horovod_local_mode_2_2_0'

    def read_json(file, tmp):
>       with open(os.path.join(tmp, file)) as f:
E       FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pytest-of-root/pytest-2/popen-gw9/test_horovod_local_mode_2_2_0/rank-0'

tests/integ/test_horovod.py:102: FileNotFoundError
----------------------------- Captured stdout call -----------------------------

**Comment by jesterhazy** [comment]
### AWS CodeBuild CI Report

* Result: FAILED
* [Build Logs](https://9dzx6wxcy9.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=fb938fe0-3b4e-44e0-ab6b-dfeaaee73f73%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by jesterhazy** [comment]
### AWS CodeBuild CI Report

* Result: FAILED
* [Build Logs](https://9dzx6wxcy9.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=38157cd9-ab7d-40ff-94c3-ae407939c085%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by jesterhazy** [comment]
### AWS CodeBuild CI Report

* Result: SUCCEEDED
* [Build Logs](https://9dzx6wxcy9.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=606785e8-32e2-47f4-af5c-0d5a7ee9873a%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by jmgray24** [comment]
Closing, as I need to change this entirely. Because of the way deploy and other methods call get_default_bucket, This will be a poor design pattern. Instead, I will need to pass the STS endpoint during SageMaker session initialization and then check STS endpoint URL in the functions.

**Pull request closed without merging**
