### PR TITLE
change: remove unused dependency protobuf3-to-dict

### PR DESCRIPTION
**Pull request by zenogantner**
*Description of changes:*

`protobuf3-to-dict` is not used by the SageMaker Python SDK, as far as I can tell.

No occurrence in the source code:
```shell
> ag protobuf_to_dict
doc/frameworks/tensorflow/upgrade_from_legacy.rst
230:    from protobuf_to_dict import protobuf_to_dict
240:    protobuf_to_dict(json_format.Parse(result, tensor_pb2.TensorProto()))
```
This dependency has not been updated since 2017 and causes issues in certain combinations of poetry and pyenv. I suggest to remove it.

*Testing done:*

Ran local tests with Python 3.10, output looked okay.

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by claytonparnell — APPROVED** [review]

**Review by claytonparnell — COMMENTED** [review]
/bot run all

**Review by claytonparnell — APPROVED** [review]

**Review by claytonparnell — COMMENTED** [review]
/bot run all

**Review by claytonparnell — COMMENTED** [review]
/bot run slow-tests

**Review by claytonparnell — COMMENTED** [review]
/bot run local-mode-tests, notebook-tests, pr, unit-tests

**Comment by zenogantner** [comment]
`sagemaker-python-sdk-pr` failed 23 days ago. Logs are available for 7 more days.

Given that different test runs failed at different times -- are these somewhat flaky tests?

**Review by vikas0203 — APPROVED** [review]

**Review by vikas0203 — COMMENTED** [review]
/bot run all

**Review by vikas0203 — COMMENTED** [review]
/bot run notebook-tests

**Review by vikas0203 — COMMENTED** [review]
/bot run slow-tests

**Review by vikas0203 — COMMENTED** [review]
/bot run all

**Comment by knikure** [comment]
@zenogantner  Thanks for taking up this change.
I have created another PR #3869 to accommodate this change. Hence closing this PR.

**Pull request closed without merging**
