### PR TITLE
fix: support specifying a facet by its column index

### PR DESCRIPTION
**Pull request by xgchena**
*Issue #, if available:*

https://tiny.amazon.com/324vu66t

*Description of changes:*

Currently the Clarify BiasConfig only accepts facet name. Actually Clarify analysis configuration supports both name and index. This commit adds the same support to BiasConfig.

*Testing done:*

* unit test passed
* review the API doc built by sphinx

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [x] I certify that the changes I am introducing will be backword compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [x] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [x] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have added unit and/or integration tests as appropriate to ensure backward compatibility of the changes
- [x] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [x] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by xgchena** [comment]
> ### AWS CodeBuild CI Report
> * CodeBuild project: sagemaker-python-sdk-slow-tests
> * Commit ID: [db1e2c2](https://github.com/aws/sagemaker-python-sdk/commit/db1e2c212d5955111f705af30d480738032baf21)
> * Result: FAILED
> * [Build Logs](https://we1smikb89.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=64073e6e-6012-4eb6-9464-d9892a6476b8%2Fbuild.log) (available for 30 days)
> 
> _Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)_

Resource limit problem of the account that run the tests.

```
botocore.errorfactory.ResourceLimitExceeded: An error occurred (ResourceLimitExceeded) when calling the CreateMonitoringSchedule operation: The account-level service limit 'ml.c5.xlarge for processing job usage' is 50 Instances, with current utilization of 50 Instances and a request delta of 1 Instances. Please contact AWS support to request an increase for this limit.[0m
```

**Comment by xgchena** [comment]
Rebase. Trigger CodeBuild jobs again to see if the resource issue is mitigated.

**Comment by xgchena** [comment]
Rebase and force push to trigger checks.

**Comment by xgchena** [comment]
Rebase and force push to trigger checks. Asking team members for review/approval.

**Review by xiaoyi-cheng — APPROVED** [review]
lgtm

**Comment by xgchena** [comment]
Shreya granted me access to the CodeBuild account to view build logs.

Below are the failure reasons and I can confirm they are not caused by changes of this PR.

* AWS CodeBuild us-west-2 (sagemaker-python-sdk-notebook-tests)

  This test failed due to "BUILD_TIMED_OUT: Build has timed out. "

* AWS CodeBuild us-west-2 (sagemaker-python-sdk-pr)

  Four test cases failed,
```
...
=========================== short test summary info ============================
FAILED tests/integ/test_kmeans.py::test_kmeans - botocore.exceptions.ClientEr...
FAILED tests/integ/test_multidatamodel.py::test_multi_data_model_deploy_pretrained_models_update_endpoint
FAILED tests/integ/test_multidatamodel.py::test_multi_data_model_deploy_pretrained_models
FAILED tests/integ/test_multidatamodel.py::test_multi_data_model_deploy_trained_model_from_framework_estimator[1.8.0-py37]
= 4 failed, 282 passed, 24 skipped, 23448 warnings, 76 rerun in 5608.81s (1:33:28) =
```

* AWS CodeBuild us-west-2 (sagemaker-python-sdk-slow-tests)

  This test failed due to "BUILD_TIMED_OUT: Build has timed out. "

**Review by navinsoni — APPROVED** [review]

**Comment by shreyapandit** [comment]
Please fix conflicts in order for us to merge, thanks!

**Review by shreyapandit — APPROVED** [review]
Needs an update from dev and resolution of conflicts

**Review by shreyapandit — CHANGES_REQUESTED** [review]
Needs an update from dev and resolution of conflicts

**Comment by xgchena** [comment]
> Needs an update from dev and resolution of conflicts

Thanks for the reminder. I have done a rebase from latest dev code.

**Comment by xgchena** [comment]
For the "conflicts": the PR doesn't really touch the files in question, I simply did a rebase from the dev branch to "resolve" them.

**Comment by xgchena** [comment]
The sagemaker-python-sdk-slow-tests failed by

```
(7 durations < 0.005s hidden.  Use -vv to show these durations.)
--
669 | =========================== short test summary info ============================
670 | FAILED tests/integ/test_multidatamodel.py::test_multi_data_model_deploy_train_model_from_amazon_first_party_estimator
671 | =========== 1 failed, 12 passed, 979 warnings in 4778.00s (1:19:37) ============
672 | ERROR: InvocationError for command /codebuild/output/src023590726/src/github.com/aws/sagemaker-python-sdk/.tox/py37/bin/pytest --cov=sagemaker --cov-append tests/integ -m slow_test -n 16 --durations 0 (exited with code 1)
```

Not caused by this PR. I will retry the test to see if this is a random issue.

**Review by navinsoni — APPROVED** [review]

**Review by BasilBeirouti — APPROVED** [review]

**Review by shreyapandit — APPROVED** [review]

**Pull request merged**
