### PR TITLE
documentation: add context for pytorch

### PR DESCRIPTION
**Pull request by teebkeng-aws**
*Issue #, if available:*

*Description of changes:* I'm adding some updates to the PyTorch docs to document a new parameter ('context') that customers can use for multi-GPU use cases. This update was brought up to the doc team by Wei Chu (@weichu), and the content has been approved by them.

*Testing done:* Ran the following tox tests locally and passed: black-check,flake8,pylint,docstyle,sphinx,doc8

Build preview: http://dev-dsk-teebkeng-2a-0310d08d.us-west-2.amazon.com/sdk_website/html/frameworks/pytorch/using_pytorch.html#load-a-model

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [ ] I certify that the changes I am introducing will be backword compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [ ] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [x] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added unit and/or integration tests as appropriate to ensure backward compatibility of the changes
- [ ] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [ ] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by waytrue17 — APPROVED** [review]
LGTM

**Review by aaronmarkham — APPROVED** [review]
LGTM, but I would suggest running this update on your fork on your own RTD instance and providing the link in the PR description... just so we're really sure that the website looks right.

**Comment by teebkeng-aws** [comment]
Staged preview: http://dev-dsk-teebkeng-2a-0310d08d.us-west-2.amazon.com/sdk_website/html/frameworks/pytorch/using_pytorch.html#load-a-model

**Review by mufaddal-rohawala — APPROVED** [review]

**Review by mufaddal-rohawala — COMMENTED** [review]
/bot run slow-tests

**Pull request merged**
