### PR TITLE
fix: Check that serializer and deserializer for predictor is a class (common error).

### PR DESCRIPTION
**Pull request by larroy**
*Description of changes:*

Added a check so the serializer and deserializers are an instance instead of a class which is a common error which can create confusion and difficult to debug errors when using predictors

*Testing done:*

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [x] I certify that the changes I am introducing will be backword compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [x] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [x] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added unit and/or integration tests as appropriate to ensure backward compatibility of the changes
- [ ] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [ ] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by ahsan-z-khan — APPROVED** [review]

**Review by keerthanvasist — APPROVED** [review]

**Comment by larroy** [comment]
Hello, what's needed here?

**Comment by larroy** [comment]
@navinsoni what's missing here?

**Review by trajanikant — COMMENTED** [review]
/bot run pr

**Review by trajanikant — COMMENTED** [review]
/bot run slow-tests

**Review by trajanikant — COMMENTED** [review]
/bot run all

**Comment by trajanikant** [comment]
@larroy Can you resolve the conflicts and get back with some updates on this?
If not we would close this and you can get back with a new PR..

**Comment by mufaddal-rohawala** [comment]
thanks for contributing but this code change has been pending for too long. Please reopen if this change is still relevant!

**Pull request closed without merging**
