### PR TITLE
feature: Add support for Native Pytorch DDP

### PR DESCRIPTION
**Pull request by satishpasumarthi**
*Issue #, if available:*

*Description of changes:*
- Add support for Vanilla PyTorch DDP
- Connected PRs:
https://github.com/aws/sagemaker-pytorch-training-toolkit/pull/231
https://github.com/aws/sagemaker-training-toolkit/pull/120

*Testing done:*

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [x] I certify that the changes I am introducing will be backword compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [x] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [ ] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have added unit and/or integration tests as appropriate to ensure backward compatibility of the changes
- [x] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [ ] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by shreyapandit** [comment]
@satishpasumarthi Please fix failing tests and update your branch for us to review this again

**Review by ahsan-z-khan — COMMENTED** [review]
is this being worked on? or we can close it for now? 
@satishpasumarthi

**Comment by satishpasumarthi** [comment]
> is this being worked on? or we can close it for now? @satishpasumarthi

Hi, Yes it is. There are other connecting parts in `sagemaker-training-toolkit` and pytorch toolkit which is being worked on. Please leave it in draft for the next few days.

**Comment by mufaddal-rohawala** [comment]
Closing as this has been in draft state for too long! Please reopen if the change is still relevant.

**Pull request closed without merging**
