### PR TITLE
fix: set sagemaker_connection and image_uri in register method

### PR DESCRIPTION
**Pull request by iasoon**
*Issue #, if available:*

*Description of changes:*
Provide a `register` method for the sklearn model, since without it the `sagemaker_connection` and `image_uri` variables are not being set, which results in an error when running this minimal code example:

```
    model = SKLearnModel(
        framework_version="0.23-1",
        py_version="py3",
        model_data=MODEL_DATA
        entry_point="serve.py",
        source_dir="./model",
        role=ROLE,
    )

    model.register(
        model_package_name=MODEL_PACKAGE_NAME,
        content_types=["text/csv"],
        response_types=["text/csv"],
        inference_instances=["ml.t2.medium"],
        transform_instances=["ml.m5.large"],
```
I adapted the `register` method from the other `FrameworkModel`s to resolve the issue.
That said, it seems like the `register` code is the same for all `FrameworkModel`s, except for the `XGBoostModel` (though the logic seems equivalent at first sight). Would it be a good idea to extract this duplication into the `FrameworkModel` class?

*Testing done:*
code snippet above

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [X] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [X] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [X] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [ ] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [ ] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by iasoon** [comment]
Is it possible that there is something off about the failing test (`tests/integ/test_mxnet.py::test_deploy_model[1.8.0-py37-1.8.0-py37]`)? It passed on the first run, but failed after I added an empty line.

**Comment by ahsan-z-khan** [comment]
@iasoon is there any particular issue/feature request for this PR?

**Comment by iasoon** [comment]
@ahsan-z-khan No, I just created this PR after running into the issue described in the original post.

**Comment by ahsan-z-khan** [comment]
@iasoon do we have an issue created for this PR?

**Comment by iasoon** [comment]
Hey @ashishgupta023, I didn't create one myself, but at a glance #2696 seems to be about the same bug.

**Review by ahsan-z-khan — APPROVED** [review]

**Pull request merged**
