### PR TITLE
Local transformer cannot deliver execution parameters

### PR DESCRIPTION
**Pull request by cosmincatalin**
`fp_closed` is `True` in `response.py` at line 503, on which response `response.read()` depends. and thus returns`b''`. Using `data` is a simple way to solve the problem and achieve the same functionality.

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [ ] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [ ] I have passed the region in to any/all clients that I've initialized as part of this change.
- [ ] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [ ] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by cosmincatalin** [comment]
@knakad, @iquintero, please review

**Comment by nadiaya** [comment]
Unit tests have failed:
```
=================================== FAILURES ======================
________________________ test_start_local_transform_job ________________________
_perform_batch_inference = <MagicMock name='_perform_batch_inference' id='139867028316432'>
_perform_request = <MagicMock name='_perform_request' id='139867023727888'>
local_transform_job = <sagemaker.local.entities._LocalTransformJob object at 0x7f355489ea50>
    @patch("sagemaker.local.entities._SageMakerContainer", Mock())
    @patch("sagemaker.local.entities._wait_for_serving_container", Mock())
    @patch("sagemaker.local.entities._perform_request")
    @patch("sagemaker.local.entities._LocalTransformJob._perform_batch_inference")
    def test_start_local_transform_job(_perform_batch_inference, _perform_request, local_transform_job):
        input_data = {}
        output_data = {}
        transform_resources = {"InstanceType": "local"}
           response = Mock()
       _perform_request.return_value = (response, 200)
        response.read.return_value = '{"BatchStrategy": "SingleRecord"}'
        local_transform_job.primary_container["ModelDataUrl"] = "file:///some/model"
>       local_transform_job.start(input_data, output_data, transform_resources, Environment={})
tests/unit/test_local_entities.py:111: _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
.tox/py27/lib/python2.7/site-packages/sagemaker/local/entities.py:182: in start
    execution_parameters = json.loads(response.data)
/usr/lib/python2.7/json/__init__.py:339: in loads
    return _default_decoder.decode(s)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <json.decoder.JSONDecoder object at 0x7f360cc28f90>
s = <Mock name='mock.data' id='139867023712016'>
_w = <built-in method match of _sre.SRE_Pattern object at 0x7f360cc5ccb0>
    def decode(self, s, _w=WHITESPACE.match):
        """Return the Python representation of ``s`` (a ``str`` or ``unicode``
        instance containing a JSON document)
        """
>       obj, end = self.raw_decode(s, idx=_w(s, 0).end())
E       TypeError: expected string or buffer
```

**Comment by laurenyu** [comment]
hi @cosmincatalin, thanks for submitting this PR. are you able to address the unit test failures? (see @nadiaya's comment: https://github.com/aws/sagemaker-python-sdk/pull/1382#issuecomment-608813707)

**Comment by cosmincatalin** [comment]
Sure.

**Comment by laurenyu** [comment]
closing due to lack of activity. feel free to reopen if you get a chance to address the unit test failures.

**Pull request closed without merging**
