### PR TITLE
change: Update data wrangler images

### PR DESCRIPTION
**Pull request by aws-patlin**
*Issue #, if available:*
https://sim.amazon.com/issues/SDW-4734

*Description of changes:*
* Add missing Data Wrangler account ID for ap-northeast-3
* Add 2.x Data Wrangler container version
* Default to latest Data Wrangler image when no version is provided

*Testing done:*
* Updated relevant tests

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [ ] I certify that the changes I am introducing will be backward compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [ ] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [ ] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added unit and/or integration tests as appropriate to ensure backward compatibility of the changes
- [x] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [ ] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by aws-patlin** [comment]
An unrelated test failed. Can the CodeBuild run be retried?

**Review by claytonparnell — APPROVED** [review]
/bot run slow-tests

**Comment by aws-patlin** [comment]
There are two consistently failing slow tests:
test_deploy_inference_recommendation_id_with_registered_model_sklearn
test_run_explainability_monitor

Are they being investigated?

**Comment by athewsey** [comment]
(Linking #3798, which this PR should also fix once merged)

**Review by claytonparnell — COMMENTED** [review]
/bot run slow-tests

**Comment by chenliu0831** [comment]
Could someone help merging this? Thanks!

**Review by knikure — APPROVED** [review]

**Pull request merged**
