### PR TITLE
feat: locations for EMR configuration and Spark dependencies

### PR DESCRIPTION
**Pull request by leandrolcampos**
*Issue #, if available:* #3200

*Description of changes:*
This PR gives the user the possibility to specify, when initializing objects of `PySparkProcessor` and `SparkJarProcessor` classes, where the EMR application configuration and Spark dependencies will be uploaded. It is inspired by the `code_location` parameter of the `FrameworkProcessor` class.

*Testing done:*
`export IGNORE_COVERAGE=- ; tox -e py310 -- -s -vv tests/unit/sagemaker/spark/test_processing.py ; unset IGNORE_COVERAGE`

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [x] I certify that the changes I am introducing will be backward compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [x] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [x] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have added unit and/or integration tests as appropriate to ensure backward compatibility of the changes
- [x] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [x] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by leandrolcampos** [comment]
Hi @claytonparnell,

I hope this message finds you well.

When you have time, could you please take a look at this?

All the best,

**Review by vikas0203 — APPROVED** [review]
/bot run all

**Review by vikas0203 — COMMENTED** [review]
/bot run all

**Review by vikas0203 — COMMENTED** [review]
/bot run pr

**Comment by leandrolcampos** [comment]
Hi @vikas0203,

I hope this message finds you well. Please let me know if I have something to change in this PR.

All the best,

**Review by vikas0203 — COMMENTED** [review]
/bot run slow-tests,pr

**Review by vikas0203 — COMMENTED** [review]
/bot run unit-tests

**Comment by leandrolcampos** [comment]
Hi @vikas0203 and @knikure,

I hope this message finds you well. Please let me know if I have something to change in this PR.

All the best,

**Comment by claytonparnell** [comment]
Hi @leandrolcampos - very sorry this has been pending for so long. It looks like there are some style issues, could you run `tox -e black-format` and `tox -e flake8` to resolve the issues? Then we will try to get this merged in.

**Comment by leandrolcampos** [comment]
Hi @claytonparnell,

I addressed your comment. Can you please review the PR again?

Thank you very much for your guidance!

**Comment by leandrolcampos** [comment]
Hi @claytonparnell,

I hope this message finds you well. Please let me know if I have something to change in this PR.

All the best,

**Review by claytonparnell — COMMENTED** [review]
/bot run all

**Comment by leandrolcampos** [comment]
Hi @claytonparnell,

Please let me know if I have something to change in this PR.

**Review by claytonparnell — COMMENTED** [review]
/bot run slow-tests

**Pull request merged**
