### PR TITLE
feature: Added a print statement for Analysis config in clarify

### PR DESCRIPTION
**Pull request by dosatos**
*Issue #, if available:*

*Description of changes:*
Added a print statement for Analysis config in clarify

*Testing done:*
no testing. I simply added a print statement.

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [x] I certify that the changes I am introducing will be backword compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [ ] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [ ] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added unit and/or integration tests as appropriate to ensure backward compatibility of the changes
- [ ] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [ ] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by larroy — COMMENTED** [review]
let's not print. Let's make a method to return it as a string and decouple concerns.

**Review by keerthanvasist — COMMENTED** [review]
@larroy what is the intent here? We write the analysis config to S3 already. I don't think we should be returning the analysis config (least of all as a string). If anything, I think we should return the processing job ID if we can. This can be useful for the customer when they are trying to automate it. 

Currently, customer can only know the processing job name from the log. Instead, it would be good if we can expose the name of the processing job or return it.

**Comment by larroy** [comment]
I think is good to have access to the analysis config file locally, is already there and also makes the code more decoupled allowing us better testability and problem diagnosis. Agree with processing job ID we should expose that as well.

**Comment by dosatos** [comment]
@keerthanvasist @larroy thank you for the feedback

The problem with returning the `analysis_config` (i.e. storing the value inside the instance) is that is is different for `run_bias`, `run_pre_training_bias`, `run_post_training_bias`, `run_explainability`. Thus, mutates each time we alternate the method. I can imaging a case when, a user runs `run_explainability`, and then `run_bias`, and then starts to debug why `run _explainability` mis-behaved by looking into `obj.analysis_config` (which is different already).

### Option 1 [not recommended]
Store analysis config for the latest executed job.

```python
@property
def analysis_config(self):
    return self.__analysis_config
```

- Advtangages: Simple to implement.
- Disadvantages: It is confusing as the config would mutate after we run different methods  (`run_bias`, `run_pre_training_bias`, `run_post_training_bias`, `run_explainability)

### Option 2:
Given this, the simplest and the most accurate is to log the `analysis_config` the `SageMakerClarifyProcessor` used to `_run` the workload. 

Example:
```
Job Name:  Clarify-Bias-2022-07-22-09-00-31-294
Inputs:  [{...}]
Outputs:  [...}]
```

- Advantages: simple to implement - solves the debugging needs. 
- Distadvantages: it polutes the std output (perhaps not a concern, as we already do inside `Processor` when print Job)

### Option 3 [recommended]
Another option is to build a factory method for the analysis configs. 
- Advantages: 
	- 1) helps debugging needs
	- 2) improves code - separation of concerns
- Disadvantages: when customer debugs, does not guarantee the person would feed the same DataConfig/Model to the Factory as to the `SageMakerClarifyProcessor` (chances are low, but possible)

**Pull request closed without merging**
