### PR TITLE
Add SMDP support for TF 2.3.2

### PR DESCRIPTION
**Pull request by indhub**
*Description of changes:*
Add SMDP support for TF 2.3.2

*Testing done:*
Tested model training with Tf 2.3.2 and SMDP

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [x] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [x] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [x] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ChoiByungWook** [comment]
I think 2.3.2 isn't supported currently: https://github.com/aws/sagemaker-python-sdk/blob/24300c256dce844a9c282b0f2a729c5623ddbb40/src/sagemaker/image_uri_config/tensorflow.json#L245

**Comment by indhub** [comment]
TF 2.3.2 for DLC is on the way. This is a proactive change.

**Comment by indhub** [comment]
Looks like DLC with TF 2.3.2 is already released. Changes to python SDK is on the way.

**Comment by indhub** [comment]
Closing this PR.
https://github.com/aws/sagemaker-python-sdk/pull/2223 handles this.

**Pull request closed without merging**
