### PR TITLE
Feature/new fg utils

### PR DESCRIPTION
**Pull request by JoseJuan98**
*Issue #, if available:*

*Description of changes:* added a few methods to automate processes to work with Feature Groups, one to prepare a FG before creation and another to extract directly a dataframe from a FG faster.
Also, I extended the method `FeatureGroup.as_dataframe()` to accept kwargs to specify some parameters in the `pandas.read_csv` use to create the dataframe as I encounter some problems with encoding and dtypes that could be fix specifying `low_memory=False` and the encoding used.

*Testing done:*
Local tests with tox following the contribution guide.

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [x] I certify that the changes I am introducing will be backward compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [x] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [x] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have added unit and/or integration tests as appropriate to ensure backward compatibility of the changes
- [x] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [x] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by navinsoni — COMMENTED** [review]
@JoseJuan98  Can you please update description with what's happening in this PR

**Comment by JoseJuan98** [comment]
> @JoseJuan98 Can you please update description with what's happening in this PR

I updated it, please let me know if something is not clear :)

**Review by navinsoni — COMMENTED** [review]
/bot run all

**Review by navinsoni — CHANGES_REQUESTED** [review]
@JoseJuan98 Can you please address unit-test and other test failures.
The failure are related to styling. you can run following command to locally to fix it

`tox -e flake8,pylint,docstyle,black-check,twine`

**Comment by JoseJuan98** [comment]
> @JoseJuan98 Can you please address unit-test and other test failures. The failure are related to styling. you can run following command to locally to fix it
> 
> `tox -e flake8,pylint,docstyle,black-check,twine`

@navinsoni I made all changes in the recents pushes, now all should be fixed

```shell
______________________________________________________ summary _______________________________________________________
  flake8: commands succeeded
  pylint: commands succeeded
  docstyle: commands succeeded
  black-check: commands succeeded
  twine: commands succeeded
  congratulations :)
```

**Comment by navinsoni** [comment]
@JoseJuan98 Can you please fix conflicts.

**Comment by JoseJuan98** [comment]
> @JoseJuan98 Can you please fix conflicts.

@navinsoni merged, conflicts solved and  the tox tests passed

**Comment by JoseJuan98** [comment]
> @JoseJuan98 Can you please fix conflicts.

@navinsoni merged and solved conflicts with the most recent  master

**Review by jpenagom — COMMENTED** [review]
Reviewed code style and docstyle

**Comment by jpenagom** [comment]
@navinsoni hi, could you give me some information about the status of this PR? Is there anything else I could do to resolve the changes requested by you?

**Comment by jpenagom** [comment]
@navinsoni hi, could you give me some information about the status of this PR? Is there anything else I could do to resolve the changes requested by you?

The sphinx build was failing, I have fixed it, now all tox tests environments suggested by you and the documentation are passing

**Review by trajanikant — COMMENTED** [review]
/bot run all

**Comment by JoseJuan98** [comment]
Hi @trajanikant, I don't have access to the logs, and the tests I made passed successfully via tox, could you give me more insights about the build failures?

**Comment by JoseJuan98** [comment]
Hi @trajanikant , I made the changes that were causing the pylint checks to fail. The rest I am not sure with what they could be related, the integrations tests of feature store displays the following message:

```
botocore.errorfactory.ResourceLimitExceeded: An error occurred (ResourceLimitExceeded) when calling the CreateFeatureGroup operation: The account-level service limit 'Maximum number of feature groups allowed per account' is 200 FeatureGroups, with current utilization of 200 FeatureGroups and a request delta of 1 FeatureGroups. Please contact AWS support to request an increase for this limit.
```

**Review by navinsoni — COMMENTED** [review]
/bot run all

**Comment by JoseJuan98** [comment]
Hi @navinsoni  and @trajanikant , I found the problems that there were previously with the Feature Group utils functionality, it has been fixed and tested. could you try to run it again please?

**Comment by JoseJuan98** [comment]
> @JoseJuan98 Can you please rebase these changes on master branch instead of merging. It is showing 42 files in diff

Hi @navinsoni , I tried to do that but anyways it rejected the push after the rebase and asked me to merge the branches before pushing, so it didn't solve it.

The only file affected by my changes are:
- src/sagemaker/feature_group_utils.py
- src/sagemaker/utils.py
- src/sagemaker/feature_store/feature_group.py
- test/unit/sagemaker/feature_store/test_feature_group_utils.py
- test/unit/sagemaker/feature_store/test_feature_group.py
- test/integ/test_feature_store.py

The rest of the file were added by the merge file.

**Comment by navinsoni** [comment]
@JoseJuan98 you will have to rebase the changes and force push it on your repo. It will be error prone to review this PR without that change.

**Comment by JoseJuan98** [comment]
> @JoseJuan98 you will have to rebase the changes and force push it on your repo. It will be error prone to review this PR without that change.

It has been very tiring and very error prompt to do that, so I decided to create a new PR using rebase, so now it only appears the new commits and the changes, please check [link](https://github.com/aws/sagemaker-python-sdk/pull/3707). 

Shall I close this PR and continue from the other one?

**Comment by navinsoni** [comment]
@JoseJuan98 Thanks for creating new PR, closing this one.

**Pull request closed without merging**
