### PR TITLE
Skip JS Tune integration test

### PR DESCRIPTION
**Pull request by makungaj1**
*Issue #, if available:*

*Description of changes:*
Skip Integration test case for JS Tune in local mode.

This test case may be suitable as Notebook test as it requires access to instance GPU count to determine
Tensor parallel degrees.

```
        admissible_parallel_degrees = []
>       for i in (n + 1 for n in reversed(range(len(available_gpus)))):
E       TypeError: object of type 'NoneType' has no len()
```

*Testing done:*

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x ] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [ x] I certify that the changes I am introducing will be backward compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [ x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [ x] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [ x] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [x ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x ] I have added unit and/or integration tests as appropriate to ensure backward compatibility of the changes
- [x ] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [ x] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by gwang111** [comment]
Whats our path to addressing this gap in testing?

**Review by gwang111 — APPROVED** [review]

**Comment by makungaj1** [comment]
> Whats our path to addressing this gap in testing?

**Comment by samruds** [comment]
This issue is arising due to instance type with GPU enabled not being picked? 

Can we use this : https://github.com/aws/sagemaker-python-sdk/blob/master/tests/integ/sagemaker/serve/test_serve_model_builder_gpu.py#L91

**Comment by makungaj1** [comment]
> This issue is arising due to instance type with GPU enabled not being picked?

Yeah, this could work if we pass instance type in `.tune()` like here https://github.com/aws/sagemaker-python-sdk/blob/master/tests/integ/sagemaker/serve/test_serve_model_builder_gpu.py#L105

Passing instance type during model builder init doesn't help either

```
model_builder = ModelBuilder(
        model="huggingface-llm-bilingual-rinna-4b-instruction-ppo-bf16",
        schema_builder=SchemaBuilder(SAMPLE_PROMPT, SAMPLE_RESPONSE),
        mode=Mode.LOCAL_CONTAINER,
        sagemaker_session=sagemaker_local_session,
        instance_type=kwargs["instance_type"],
    )
```

Note: As this test case was recently added. I'll completely remove it.

**Comment by akrishna1995** [comment]
> > This issue is arising due to instance type with GPU enabled not being picked?
> 
> Yeah, this could work if we pass instance type in `.tune()` like here https://github.com/aws/sagemaker-python-sdk/blob/master/tests/integ/sagemaker/serve/test_serve_model_builder_gpu.py#L105
> 
> Passing instance type during model builder init doesn't help either
> 
> ```
> model_builder = ModelBuilder(
>         model="huggingface-llm-bilingual-rinna-4b-instruction-ppo-bf16",
>         schema_builder=SchemaBuilder(SAMPLE_PROMPT, SAMPLE_RESPONSE),
>         mode=Mode.LOCAL_CONTAINER,
>         sagemaker_session=sagemaker_local_session,
>         instance_type=kwargs["instance_type"],
>     )
> ```
> 
> Note: As this test case was recently added. I'll completely remove it.

Thank you so much!

**Review by akrishna1995 — APPROVED** [review]

**Pull request merged**
