### PR TITLE
change: Upgrade DJL deepspeed versions

### PR DESCRIPTION
**Pull request by lanking520**
*Description of changes:*

Update the container image of DLC.

*Testing done:*

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [x] I certify that the changes I am introducing will be backward compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [x] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [x] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have added unit and/or integration tests as appropriate to ensure backward compatibility of the changes
- [x] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [x] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by frankfliu — APPROVED** [review]

**Review by knikure — COMMENTED** [review]
/bot run all

**Review by siddvenk — APPROVED** [review]

**Review by frankfliu — APPROVED** [review]

**Review by knikure — COMMENTED** [review]
/bot run all

**Comment by davidthomas426** [comment]
@lanking520 Looking at the logs, looks like a change is needed here too: https://github.com/aws/sagemaker-python-sdk/blob/master/tests/unit/sagemaker/image_uris/test_huggingface_llm.py#L52

**Comment by davidthomas426** [comment]
The notebook test check failures are unrelated to this change:
```
...
./amazon-sagemaker-examples/sagemaker-python-sdk/mxnet_onnx_export/mxnet_onnx_export.ipynb: TIMED_OUT (PT11M38.586S)
```

**Comment by lanking520** [comment]
Just rebase the master. @knikure could we merge this PR since it only introduce small changes?

**Review by knikure — APPROVED** [review]

**Comment by knikure** [comment]
@lanking520 Can you fix  the failing unit-test?
`tests/unit/sagemaker/image_uris/test_huggingface_llm.py:78: AssertionError`

**Comment by davidthomas426** [comment]
> oking at the logs, looks like a change is neede

Check

> @lanking520 Looking at the logs, looks like a change is needed here too: https://github.com/aws/sagemaker-python-sdk/blob/master/tests/unit/sagemaker/image_uris/test_huggingface_llm.py#L52

Not sure if you saw this before, but this unit test is failing at this point.

**Comment by lanking520** [comment]
@knikure just rebased the changes, let's see

**Review by frankfliu — APPROVED** [review]

**Comment by davidthomas426** [comment]
The unit tests succeeded this time.

The notebook test failures are unrelated to this change:
```
TIMED_OUT	./amazon-sagemaker-examples/sagemaker-python-sdk/mxnet_onnx_export/mxnet_onnx_export.ipynb	PT4M32.953S
...
TIMED_OUT	./amazon-sagemaker-examples/sagemaker-python-sdk/1P_kmeans_highlevel/kmeans_mnist.ipynb	PT9M28.25S
...
TIMED_OUT	./amazon-sagemaker-examples/sagemaker-python-sdk/scikit_learn_randomforest/Sklearn_on_SageMaker_end2end.ipynb	PT12M18.844S
```

**Pull request merged**
