### PR TITLE
3826: Fix LambdaStep Creation

### PR DESCRIPTION
**Pull request by dipanjank**
*Issue #, if available:*
#3826 

*Description of changes:*

* Fix LambdaStep Creation with suitable defaults for ``vpc_config``, ``environment`` and ``layers`` when they are not specified by the caller. (dict, dict and list, respectively).

* In addition. removed the ``architectures`` argument. This argument is not supported completely in boto3 Lambda client's ``create_function`` method and so it would have never worked.  Even though it is documented, specifying it generates an "invalid parameter" error, e.g.

```python
def create_function():
    lambda_client = boto3.client("lambda")
    response = lambda_client.create_function(
        FunctionName="hello_world",
        Runtime="python3.9",
        Handler="lambda_handler",
        Role="arn:aws:iam::<account-id>:role/service-role/test_hello-role-vomn97mn",
        Code={"ZipFile": build_code()},
        VpcConfig={},
        Environment={},
        Layers=[],
        Architectures=["x86-64"],
    )
    print(response)
```

Output:

```python
Traceback (most recent call last):
  File "/Users/dipanjan.kailthya@TMNL.nl/Library/Application Support/JetBrains/PyCharm2022.3/scratches/scratch_93.py", line 42, in <module>
    create_function(lc)
  File "/Users/dipanjan.kailthya@TMNL.nl/Library/Application Support/JetBrains/PyCharm2022.3/scratches/scratch_93.py", line 16, in create_function
    Architectures=["x86-64"],
  File "/Users/dipanjan.kailthya@TMNL.nl/opt/anaconda3/envs/dev/lib/python3.6/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/dipanjan.kailthya@TMNL.nl/opt/anaconda3/envs/dev/lib/python3.6/site-packages/botocore/client.py", line 678, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/Users/dipanjan.kailthya@TMNL.nl/opt/anaconda3/envs/dev/lib/python3.6/site-packages/botocore/client.py", line 726, in _convert_to_request_dict
    api_params, operation_model)
  File "/Users/dipanjan.kailthya@TMNL.nl/opt/anaconda3/envs/dev/lib/python3.6/site-packages/botocore/validate.py", line 337, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in input: "Architectures", must be one of: FunctionName, Runtime, Role, Handler, Code, Description, Timeout, MemorySize, Publish, VpcConfig, PackageType, DeadLetterConfig, Environment, KMSKeyArn, TracingConfig, Tags, Layers, FileSystemConfigs, ImageConfig, CodeSigningConfigArn
```

*Testing done:*
 
```shell
$ pytest tests/unit/test_lambda_helper.py 
================================================================================================= test session starts ==================================================================================================
platform darwin -- Python 3.9.12, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /Users/dipanjan.kailthya@TMNL.nl/PycharmProjects/sagemaker-python-sdk, configfile: tox.ini
plugins: timeout-2.1.0, rerunfailures-10.2, xdist-2.4.0, anyio-3.6.2, forked-1.6.0, cov-3.0.0
collected 28 items                                                                                                                                                                                                     

tests/unit/test_lambda_helper.py ............................                                                                                                                                                    [100%]

============================================================================================ 28 passed in 63.52s (0:01:03) ============================================================================================
```

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [ ] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [ ] I certify that the changes I am introducing will be backward compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [ ] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [ ] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [ ] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [X] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [X] I have added unit and/or integration tests as appropriate to ensure backward compatibility of the changes
- [ ] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [ ] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by hxrsmurf — APPROVED** [review]
LGTM

**Review by qidewenwhen — APPROVED** [review]

**Review by knikure — COMMENTED** [review]
/bot run all

**Review by knikure — COMMENTED** [review]
/bot run all

**Comment by dipanjank** [comment]
Hi @knikure the branch keeps getting out of date - do you want me to update it now?

**Review by mufaddal-rohawala — APPROVED** [review]

**Pull request merged**
