### PR TITLE
doc: clarify that entry_point must be in the root of source_dir (if applicable)

### PR DESCRIPTION
**Pull request by laurenyu**
*Issue #, if available:*

*Description of changes:*
It's been assumed but not explicitly stated that `entry_point` can't contain a path if `source_dir` is also supplied, so this change fixes that. I also removed mention of Python version compatibility in these docstrings, as which frameworks support which versions has changed, and is documented elsewhere.

*Testing done:*

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [ ] I have passed the region in to any/all clients that I've initialized as part of this change.
- [x] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [ ] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by laurenyu** [comment]
@litaws there's no technical reason we can't make the change. I'd started on it awhile ago (#941), but then ran into needing to make changes to the images to allow it. That's since been done, but I haven't had the chance yet to revisit my old PR.

**Comment by litaws** [comment]
1) So I should follow #941, and if it is resolved I should be able to use a file not in the root?
2) What about local code mode? (#941 is only for S3)

**Comment by laurenyu** [comment]
for #2, can you open a new issue? the [code](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/fw_utils.py#L452) doesn't look like it strips the entry point's path, but this would be better tracked in an issue

**Comment by litaws** [comment]
I will open an issue, but just note that the [code does indeed strip the path](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/estimator.py#L1685)

**Pull request merged**
