### PR TITLE
change: turn on warnings as errors for docs builds

### PR DESCRIPTION
**Pull request by aaronmarkham**
*Description of changes:*
Turns on warnings as errors for Sphinx builds. This will enforce that new changes cannot break the documentation. Without this, contributors might still pass CI without realizing that they broke the docs.

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by aaronmarkham** [comment]
Let's discuss the impact of this prior to merging. Others should try this out to make sure they're comfortable with enforcing this.

**Comment by laurenyu** [comment]
does this conflict at all with #631?

**Comment by nadiaya** [comment]
We already have this for when the readthedocs builds documentation:
https://github.com/aws/sagemaker-python-sdk/pull/631

and we have this flag when running tox as part of CI:
https://github.com/aws/sagemaker-python-sdk/pull/653
https://github.com/aws/sagemaker-python-sdk/blob/master/tox.ini#L116
https://github.com/aws/sagemaker-python-sdk/blob/master/buildspec-unittests.yml#L14

I also don't think that particular command is used outside of building docs locally for manual testing.

**Comment by aaronmarkham** [comment]
> We already have this for when the readthedocs builds documentation:
> #631
> 
> and we have this flag when running tox as part of CI:
> #653
> https://github.com/aws/sagemaker-python-sdk/blob/master/tox.ini#L116
> https://github.com/aws/sagemaker-python-sdk/blob/master/buildspec-unittests.yml#L14
> 
> I also don't think that particular command is used outside of building docs locally for manual testing.

Ok this is good! But I think it's helpful to have it checking when you're developing and testing your changes. That way you know you have an issue even before you submit your PR.

**Comment by laurenyu** [comment]
@aaronmarkham sorry, can you merge from master again?

**Comment by laurenyu** [comment]
@aaronmarkham sorry, can you merge from master again? (is there a setting where you can allow us to merge from master in the UI?)

**Comment by laurenyu** [comment]
> Ok, synced it up again... should we just merge this once it passes the tests?

thanks, just merged it! the PR has to be up-to-date with master before it can be merged, so sometimes it's just a matter of timing. I'm not sure why on your PRs there's not a button for us to merge from master for you like there is with other PRs.

**Pull request merged**
