### PR TITLE
fix: preserve model_dir bool value

### PR DESCRIPTION
**Pull request by ChuyangDeng**
*Issue #, if available:*
`TensorFlow` estimator's param `model_dir` will be changed to `None` if it was set to `False` by user after `.hyperparameter()` is called in https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/estimator.py#L1116-L1117 (`.hyperparameters()` called twice). It will later get set to a default s3 value when it's called the second time because its value is no longer `False` https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/tensorflow/estimator.py#L319.

*Description of changes:*
Adding a `disable_model_dir` param to `TensorFlow` class to make sure the boolean value is used as intended.
Corresponding change in sagemaker-tensorflow-training-toolkit: https://github.com/aws/sagemaker-tensorflow-training-toolkit/pull/403

*Testing done:*
`tox -e py38 -- tests/unit`
`tox -e py38 -- tests/component/test_tf_estimator.py`

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [ ] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [ ] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [ ] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by icywang86rui** [comment]
Can we fix it in https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/estimator.py#L1116-L1117
by assigning the result of hyperparamter() and eliminate the send call?

**Comment by icywang86rui** [comment]
or if you want to limit blast radius fix it here - https://github.com/aws/sagemaker-python-sdk/blob/21ef053d54929e53e2927bded4deff02ce7e5f83/src/sagemaker/tensorflow/estimator.py#L320-L321

`additional_hyperparameters["model_dir"] = self.model_dir or self._default_s3_path("model", mpi=mpi_enabled)`

**Comment by ChuyangDeng** [comment]
> or if you want to limit blast radius fix it here -
> 
> https://github.com/aws/sagemaker-python-sdk/blob/21ef053d54929e53e2927bded4deff02ce7e5f83/src/sagemaker/tensorflow/estimator.py#L320-L321
> 
> `additional_hyperparameters["model_dir"] = self.model_dir or self._default_s3_path("model", mpi=mpi_enabled)`

This will also result in setting `additional_hyperparameters["model_dir"]` to a default s3 uri if `self.model_dir` is `None`.

I will try with making changes here: https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/estimator.py#L1116-L1117 (I was hesitant at first because I was afraid it might break something else, but I will make sure it doesn't)

**Comment by icywang86rui** [comment]
> > or if you want to limit blast radius fix it here -
> > https://github.com/aws/sagemaker-python-sdk/blob/21ef053d54929e53e2927bded4deff02ce7e5f83/src/sagemaker/tensorflow/estimator.py#L320-L321
> > 
> > `additional_hyperparameters["model_dir"] = self.model_dir or self._default_s3_path("model", mpi=mpi_enabled)`
> 
> This will also result in setting `additional_hyperparameters["model_dir"]` to a default s3 uri if `self.model_dir` is `None`.
> 
> I will try with making changes here: https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/estimator.py#L1116-L1117 (I was hesitant at first because I was afraid it might break something else, but I will make sure it doesn't)

you can make it explicit by adding another if statement

**Review by icywang86rui — APPROVED** [review]

**Review by metrizable — APPROVED** [review]

**Pull request merged**
