### PR TITLE
fix: map user context is list associations response

### PR DESCRIPTION
**Pull request by danabens**
map UserContext from the ListAssociations response

```python
tox -e py38 -- tests/unit/sagemaker/lineage/test_association.py -k 'test_list' -vv
```

### CODE REVIEW

**Review by stisac — APPROVED** [review]

**Review by stisac — APPROVED** [review]

**Comment by danabens** [comment]
currently investigating test failures, was able to run tests successfully locally.

**Review by icywang86rui — COMMENTED** [review]
Please add an integ test or modify an existing one.

**Comment by danabens** [comment]
> Please add an integ test or modify an existing one.

Modified an existing integ test to the extent possible.

**Comment by danabens** [comment]
failure unrelated

> FAILED  ./amazon-sagemaker-examples/sagemaker-python-sdk/tensorflow_script_mode_quickstart/tensorflow_script_mode_quickstart.ipynb  PT9M34.226S

**Review by stisac — APPROVED** [review]

**Review by ajaykarpur — APPROVED** [review]

**Review by stisac — APPROVED** [review]

**Pull request merged**
