### PR TITLE
Adding DCA/LCK Neo Configurations

### PR DESCRIPTION
**Pull request by TusharKanekiDey**
*Issue #, if available:*
Adding DCA/LCK Neo Configurations

*Description of changes:*
Adding DCA/LCK Neo Configurations

*Testing done:*
Minor changes.

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [ x] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [ x] I certify that the changes I am introducing will be backword compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [ x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [ x] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [ x] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by HappyAmazonian — APPROVED** [review]

**Comment by navinsoni** [comment]
@TusharKanekiDey Can please fix unit tests.

**Review by navinsoni — COMMENTED** [review]
/bot run unit-tests

**Review by navinsoni — CHANGES_REQUESTED** [review]
Please fix unit-tests

**Comment by HappyAmazonian** [comment]
We have another PR with the corrected unit tests for this. That one is merged

**Comment by navinsoni** [comment]
@HappyAmazonian Can you please link that PR here and close this one.

**Comment by HappyAmazonian** [comment]
> @HappyAmazonian Can you please link that PR here and close this one.

- https://github.com/aws/sagemaker-python-sdk/pull/3485


I don't own this PR so I can't close it. @TusharKanekiDey

**Pull request closed without merging**
