### PR TITLE
documentation: Update description of CreateFeatureGroup and DeleteFeatureGroup for in-memory tier

### PR DESCRIPTION
**Pull request by mwfongAWS**
*Issue #, if available:*

*Description of changes:*
documentation: Update description of CreateFeatureGroup and DeleteFeatureGroup to include time to create/delete for new in-memory tier for online store feature groups.

*Testing done:*
Following testing here (doc changes): https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#build-and-test-documentation
twine: succeeded
sphinx: failed, but the error is here
.../sagemaker-python-sdk/doc/doc_utils/pretrainedmodels.rst:4407:Duplicate explicit target name: "all-pretrained-models".

From my understanding this is a common issue for local builds and shouldn't be an issue for the PR bot. Please let me know if there are any other tests you would like for me to do. Thanks!

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [x] I certify that the changes I am introducing will be backward compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [ ] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [x] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added unit and/or integration tests as appropriate to ensure backward compatibility of the changes
- [ ] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [ ] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by knikure — COMMENTED** [review]
/bot run all

**Comment by mwfongAWS** [comment]
Hi Kalyani! I'm not familiar with the error below. If there is anything I am supposed to do, can you please give me suggestions to fix?

fatal error: An error occurred (404) when calling the HeadObject operation: Key "codecov_original" does not exist
CodeCov script does not exist, please check the SDK CLI bucket for this account, stopping

**Comment by mwfongAWS** [comment]
Made the changes in my branch! Please let me know if there is anything else I need to do. Thank you!

**Comment by knikure** [comment]
@mwfongAWS Can you resolve conflicts and take latest rebase from `aws:master`?

**Comment by mwfongAWS** [comment]
I'm sorry I'm confused. I don't usually update these docs can you please help me with finding the conflicts? I believed I fixed the white space errors before and synced my fork

**Review by mwfongAWS — COMMENTED** [review]
I got rid of the whitespaces here

**Review by mwfongAWS — COMMENTED** [review]
Sorry I meant here. Are there other conflicts?

**Review by knikure — COMMENTED** [review]
/bot run all

**Pull request closed without merging**
