### PR TITLE
Use pytest instead of py.test per upstream recommendation, #dropthedot

### PR DESCRIPTION
**Pull request by scop**
*Description of changes:*

http://blog.pytest.org/2016/whats-new-in-pytest-30/
https://twitter.com/hashtag/dropthedot

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

- [x] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have updated the [changelog](https://github.com/aws/sagemaker-python-sdk/blob/master/CHANGELOG.rst) with a description of my changes (if appropriate)
- [x] I have updated any necessary [documentation](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by andremoeller** [comment]
Hey @scop ,

Seems like I can't merge this in because it's merging in from an "unknown repository" -- do you still have a fork of this repository?

Thanks!

**Comment by scop** [comment]
I don't, but "unknown repository" shouldn't prevent merging it, several other projects have been able to do that for similar pull requests. (Such a thing results when I delete my fork before a PR from it has been merged; it's something I tend to do for various drive-by contributions.)

Anyway, if you can't merge it the usual way, you can grab a "git am"able patch at https://github.com/aws/sagemaker-python-sdk/commit/8dea405a7972425b2e46e1e17ee3780ebd7ecad7.patch

**Comment by andremoeller** [comment]
@scop ,

Got it. For some reason, I can't merge it through the UI (the button is greyed out). We'll get this in anyway though, thanks!

**Comment by laurenyu** [comment]
I was able to get the commit, but given how many commits have been pushed to master since this was opened, I've recreated this PR in #249

**Pull request closed without merging**
