### PR TITLE
feat: Deploy uncompressed ML model from S3 to SageMaker Hosting endpoints

### PR DESCRIPTION
**Pull request by wuyrush**
*Issue #, if available:*

n/a

*Description of changes:*

This change supports deployment of uncompressed ML model from S3 to SageMaker Hosting endpoints. It makes the feature available to customers via existing `Estimator`, `Session` and `Model` constructs and their sub-classes. Along with [uncompressed model upload support in SageMaker Training](https://github.com/aws/sagemaker-python-sdk/commit/6d42cc8faea8913b3ee365580b1daad8d9b7dea9), this feature enables customers to train uncompressed ML model on SageMaker Training and deploy the trained model to SageMaker Hosting with existing SageMaker python SDK use pattern.

Per https://docs.aws.amazon.com/sagemaker/latest/dg/large-model-inference-uncompressed.html

*Testing done:*
- Unit tests
- Used the feature to deploy an uncompressed ML model from S3 to SageMaker Hosting:

```
from sagemaker.mxnet.model import MXNetModel

mxnet_model = MXNetModel(
    role='arn:aws:iam::123456789012:role/TestSageMakerRole',
    model_data={
        'S3DataSource': {
            'CompressionType': 'None',
            'S3DataType': 'S3Prefix',
            'S3Uri': 's3://test-bucket/uncompressed/maeve-integtest-mxnet-model/',
        }
    },
    image_uri='763104351884.dkr.ecr.us-west-2.amazonaws.com/mxnet-inference:1.8.0-cpu-py37-ubuntu16.04',
)

predictor = mxnet_model.deploy(
    initial_instance_count=1,
    instance_type='ml.m5.large',
    endpoint_name='sm-py-sdk-uncompressed-test-mxnet',
)
----!
```

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [x] I certify that the changes I am introducing will be backward compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [ ] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [x] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have added unit and/or integration tests as appropriate to ensure backward compatibility of the changes
- [x] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [ ] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by knikure — COMMENTED** [review]
/bot run all

**Comment by knikure** [comment]
@wuyrush Can you fix the black-check errors by running `tox -e black-format` command?
Submit your changes after successfully running `./.githooks/pre-push` command.

**Comment by wuyrush** [comment]
> Can you fix the black-check errors by running `tox -e black-format` command? Submit your changes after successfully running `./.githooks/pre-push` command.

Thanks for the tip. Updated the PR. I believe I had fixed all per output of `./.githooks/pre-push` except some pylint error which is irrelevant to this PR.

**Comment by knikure** [comment]
@wuyrush Can some one from your team also review the PR?

**Review by knikure — APPROVED** [review]

**Pull request merged**
