### PR TITLE
fix: properly close files in lineage queries and tests

### LINKED ISSUE #4458: More unclosed files in source and tests
**Describe the bug**

Continuing from #4456 there's more unclosed files in src and tests. Use with statements so they are always closed. May help reduce flakey tests since most of them are in tests.

I'll submit a PR to fix these separately since they are less impactful/user facing than #4456.

```console
rg  -e '[^with] open\('  ./src/ ./tests/
./tests/unit\sagemaker\workflow\test_repack_model_script.py
35:    open(fake_model_path, "w")
75:    open(fake_model_path, "w")
119:    open(fake_model_path, "w")

./tests/unit\sagemaker\serializers\test_serializers.py
348:    validation_image_data = open(validation_image_file_path, "rb").read()
356:    validation_image_data = open(validation_image_file_path, "rb").read()

./tests/unit\sagemaker\local\test_local_image.py
371:        open(os.path.join(volume, f), "a").close()

./tests/unit\sagemaker\config\test_config.py
37:    return open(config_file_path, "r").read()
231:    config_file_as_yaml = open(config_file_content_path, "r").read()

./tests/integ\test_sagemaker_config.py
174:    config_file_1_as_yaml = open(config_file_1_local_path, "r").read()

./tests/integ\sagemaker\workflow\test_workflow.py
546:        json.dump(ingestion_only_flow, open(temp_flow_path, "w"))

./tests/integ\sagemaker\lineage\test_lineage_visualize.py
145:        fo = open("testGraph.html", "r")

./tests/integ\lock.py
30:    f = open(path, "w")

./tests/data\sip\training.py
76:    pkl.dump(bst, open(model_dir + "/model.bin", "wb"))

./src/sagemaker\lineage\query.py
338:        f = open(path, "r")

```

**To reproduce**
A clear, step-by-step set of instructions to reproduce the bug.
The provided code need to be **complete** and **runnable**, if additional data is needed, please include them in the issue.

Run pytest with warnings as errors, there will be resource warnings for unclosed files.

```bash
python -X dev -X tracemalloc=20 -m pytest ./tests/unit/ -W error
```

**Expected behavior**

Don't leak files.

**Screenshots or logs**
If applicable, add screenshots or logs to help explain your problem.

**System information**
A description of your system. Please provide: windows
- **SageMaker Python SDK version**: master
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: n/a
- **Framework version**: n/a
- **Python version**: 3.11
- **CPU or GPU**: cpu
- **Custom Docker image (Y/N)**: n

**Additional context**

### PR DESCRIPTION
**Pull request by jmahlik**
Closes #4458

*Issue #, if available:*
#4458

*Description of changes:*
Close files in the tests. There was one in lineage that's user facing.

*Testing done:*
Need to run the ci. Tested the unit tests where I could.

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [x] I certify that the changes I am introducing will be backward compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [x] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [x ] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have added unit and/or integration tests as appropriate to ensure backward compatibility of the changes
- [x] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [x] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by knikure — COMMENTED** [review]
/bot run all

**Comment by mufaddal-rohawala** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-unit-tests
* Commit ID: 3ba664bba493247044af15eaa645b145e8ad9a41
* Result: FAILED
* [Build Logs](https://fegcnxu6da.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=5fe1fbc9-bd2f-4ea2-acc3-4cb09d04a8d5%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by mufaddal-rohawala** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-local-mode-tests
* Commit ID: 3ba664bba493247044af15eaa645b145e8ad9a41
* Result: FAILED
* [Build Logs](https://8huhkqo601.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=95e41195-d7b4-48bf-a0d7-1d26182aee61%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by mufaddal-rohawala** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 3ba664bba493247044af15eaa645b145e8ad9a41
* Result: SUCCEEDED
* [Build Logs](https://bkqkixfb59.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=5aa71e42-b9d0-4449-85cd-8b6f637c3fdf%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by mufaddal-rohawala** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-pr
* Commit ID: 3ba664bba493247044af15eaa645b145e8ad9a41
* Result: SUCCEEDED
* [Build Logs](https://abkt2mlh3k.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=544c53de-9536-4d60-9c3c-198e27bf2135%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by mufaddal-rohawala** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-slow-tests
* Commit ID: 3ba664bba493247044af15eaa645b145e8ad9a41
* Result: SUCCEEDED
* [Build Logs](https://omfrydptb9.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=6508d671-bc53-4651-929f-e93aa4330f7a%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Review by knikure — COMMENTED** [review]
/bot run local-mode-tests, unit-tests

**Comment by mufaddal-rohawala** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-local-mode-tests
* Commit ID: 3ba664bba493247044af15eaa645b145e8ad9a41
* Result: SUCCEEDED
* [Build Logs](https://8huhkqo601.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=06eb3583-ac6e-4b14-a6ec-d1d0d2ff109f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by mufaddal-rohawala** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-unit-tests
* Commit ID: 3ba664bba493247044af15eaa645b145e8ad9a41
* Result: FAILED
* [Build Logs](https://fegcnxu6da.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=5a86c8ee-41fa-4851-8e65-575a86f16d44%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by jmahlik** [comment]
> @jmahlik Thanks for your contribution. Will you be able to create a new PR for the same change. It seems since your PR is old, the PR checks are not getting triggered correctly.

Sure can.

**Comment by jmahlik** [comment]
Replaced with https://github.com/aws/sagemaker-python-sdk/pull/4587

**Pull request closed without merging**
