### PR TITLE
fix: Fix type annotations

### PR DESCRIPTION
**Pull request by stevenmanton**
*Description of changes:*

The type annotations are backwards, so I fixed them.

*Testing done:*

None

### CODE REVIEW

**Review by claytonparnell — APPROVED** [review]

**Review by claytonparnell — COMMENTED** [review]
/bot run all

**Review by claytonparnell — COMMENTED** [review]
/bot run all

**Review by claytonparnell — COMMENTED** [review]
/bot run slow-tests

**Review by claytonparnell — COMMENTED** [review]
/bot run slow-tests

**Comment by ivan-khvostishkov** [comment]
Note, there are two places in `src/sagemaker/spark/processing.py`, which need this swap. This PR will provide the more complete explanation and fix: #3444 .

**Review by mufaddal-rohawala — APPROVED** [review]

**Pull request merged**
