### PR TITLE
Removed old link and incorrect information from estimator.py docstring

### PR DESCRIPTION
**Pull request by judyheflin**
*Description of changes:* Changed MXNet estimator.py doctstring. Standardized formatting. Removed dead link. Removed information about `framework_version` and `py_version` being required unless an image_uri is provided. Customers ran into errors where the framework_version is needed even though they provided an image_uri. 

*Remaining Questions:* 
- If the `None` default value causes an error, shouldn't we change the default value or remove it entirely? 
- Does it cause an error when you allow the default `None` value for the py_version as well?
- Does providing a version number that is different from the exact version provided in the container image cause an error?
- How can a customer easily find the exact version of Python or MXNet that is provided in their container image? 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by shreyapandit** [comment]
Hi @judyheflin please setup the Git Hooks as mentioned in README and fix the unit tests by running them locally. The sagemaker-bot comments above will guide you for the PR failures.

Have we addressed all remaining open questions and is this ready for review or still WIP?

**Comment by judyheflin** [comment]
> Hi @judyheflin please setup the Git Hooks as mentioned in README and fix the unit tests by running them locally. The sagemaker-bot comments above will guide you for the PR failures.
> 
> Have we addressed all remaining open questions and is this ready for review or still WIP?

Still waiting on a response to these questions. @amzahsa said he was taking a look, but not sure if he's still OOO.

**Review by ahsan-z-khan — CHANGES_REQUESTED** [review]
`black-check` failed. Can you do a `tox -e black-format` and commit?

**Comment by vikas0203** [comment]
@judyheflin Please resolve merge conflicts.

**Comment by mufaddal-rohawala** [comment]
thanks for contributing but this code change has been pending for too long. Please reopen if this change is still relevant!

**Pull request closed without merging**
