### PR TITLE
fix: adding .lower() so new Pandas dtypes will match the type lookup.

### PR DESCRIPTION
**Pull request by brifordwylie**
Issue #2868

*Description of changes:*
Added .lower() after Pandas dtype string cast, so that the new Pandas dtypes (which start with capitals e.g… Int64) will match the type lookup.

*Testing done:*
Unit tests: `tox tests/unit`

I'm not sure why 3 of the tests failed.. :(
```
FAILED tests/unit/sagemaker/jumpstart/test_cache.py::test_jumpstart_local_metadata_override_header - AssertionError: Expected 'open...
FAILED tests/unit/sagemaker/jumpstart/test_cache.py::test_jumpstart_local_metadata_override_specs - botocore.exceptions.ConfigParse...
FAILED tests/unit/sagemaker/jumpstart/test_cache.py::test_jumpstart_local_metadata_override_specs_not_exist_both_directories - Asse...
======================== 3 failed, 8511 passed, 3489 skipped, 3 xpassed, 3558 warnings
```

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [ ] I certify that the changes I am introducing will be backward compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [ ] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [ ] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added unit and/or integration tests as appropriate to ensure backward compatibility of the changes
- [ ] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [ ] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by mufaddal-rohawala — APPROVED** [review]

**Review by mufaddal-rohawala — APPROVED** [review]
/bot run all

**Comment by brifordwylie** [comment]
@mufaddal-rohawala thanks for the approval... I'm assuming one of the SDK devs will merge it in when they get a chance...  big thanks to all the folks putting effort into this package, it's super nice.

**Comment by brifordwylie** [comment]
I hate to bug.. but I have a downstream project that relies on this fix, could some nice person merge this when they get a chance? @mufaddal-rohawala

**Review by mufaddal-rohawala — COMMENTED** [review]
/bot run all

**Comment by mufaddal-rohawala** [comment]
@brifordwylie thanks for contributing. I'l get this PR merged by tomorrow. Please dont update from master to avoid PR check reruns.

**Review by mufaddal-rohawala — COMMENTED** [review]
/bot run all

**Pull request merged**
