### PR TITLE
add new sklearn release 1.0-1

### PR DESCRIPTION
**Pull request by lorenzwalthert**
*Issue #, if available:*

#3061 

*Description of changes:*

Add support for new scikit learn framework version. There were two previously supported versions:

* 0.20.0
* 0.23-1

I have replaced all instances of the version 0.23-1 with 1.0-1 in python source files. Documentation examples were also adapted where appropriate, some of them alos had 0.20.0. However, there were still some (integration) tests, documentation and CLI functionality that used the 0.20.0 version. Please advise what to do there, I currenlty left these unchanged.

*Testing done:*

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [x] I certify that the changes I am introducing will be backword compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [x] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [x] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have added unit and/or integration tests as appropriate to ensure backward compatibility of the changes
- [x] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [x] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by lorenzwalthert** [comment]
@secastillo can you help. Without this change, the new image is not easily usable for many users.

**Comment by lorenzwalthert** [comment]
Thanks @secastillo to pick this up in https://github.com/aws/sagemaker-python-sdk/pull/3110. A ping for this PR or a reference to the issue would have been nice to keep track of this. Found out it was solved in #3110 by chance.

**Comment by navinsoni** [comment]
@lorenzwalthert is this issue resolved for you. If yes can you please close this PR.

**Comment by lorenzwalthert** [comment]
I am not familiar enough with this package but one difference between this PR and #3110 is that here I also adapt the tests. But it has accumulated merge conflicts so let’s just close it and trust you have Integration tests elsewhere.

**Pull request closed without merging**
