### PR TITLE
fix: Prevent passing PipelineVariable object into image_uris.retrieve

### PR DESCRIPTION
**Pull request by qidewenwhen**
*Issue #, if available:* https://github.com/aws/sagemaker-python-sdk/issues/3024 

*Description of changes:*
- Raise Error to prevent users from passing in `PipelineVariable` object into `image_uris.retrieve`. The reason is, the `image_uris.retrieve` retrieve images in compile time (PySDK) while the `PipelineVariable` is parsed in runtime (Pipeline backend).
- Update the error message thrown in `__str__` defined in `PipelineVariable` to make it more informative

*Testing done:*
- unit tests

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [X] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [ ] I certify that the changes I am introducing will be backword compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [X] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [X] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [X] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [X] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [X] I have added unit and/or integration tests as appropriate to ensure backward compatibility of the changes
- [X] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [X] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by navaj0** [comment]
What is the reason for this method returning the wrong result? Is it because the __startwith__() method always return False?

**Comment by qidewenwhen** [comment]
> What is the reason for this method returning the wrong result? Is it because the **startwith**() method always return False?

No. The reason is: at this moment, it's using the **default value** of `ParameterString` for all str operations to retrieve the image. For example:[regex match](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/image_uris.py#L283).

As mentioned in this [issue](https://github.com/aws/sagemaker-python-sdk/issues/3024#issuecomment-1078355990), the user input a parameterized `instance_type` to this method. If users update the `instance_type` in runtime, the `image_uri` is not updated accordingly.

**Review by mufaddal-rohawala — APPROVED** [review]

**Comment by qidewenwhen** [comment]
@mufaddal-rohawala thanks for the review!
There're still some changes need to append to this PR. I'll update the PR next week. 
Sorry that I should have converted it to draft earlier.

**Review by staubhp — APPROVED** [review]

**Comment by qidewenwhen** [comment]
> @mufaddal-rohawala thanks for the review! There're still some changes need to append to this PR. I'll update the PR next week. Sorry that I should have converted it to draft earlier.

Changes are added. Ready for review now.

**Review by jerrypeng7773 — APPROVED** [review]

**Review by navinsoni — APPROVED** [review]

**Pull request merged**
