### PR TITLE
fix: add environment key to model container only if it is not empty

### PR DESCRIPTION
**Pull request by l3ku**
*Issue #, if available:*
#3397

*Description of changes:*
Removed defaulting to empty environment variables in the container definition to be provided to the CreateModelPackage API call. The empty dict caused a problem when trying to create a model (CreateModel API call) with some environment variables so that the model package can be used in an endpoint: environment variable map cannot be specified both at Model Package {} and Model {...}.

Fixes: aws/sagemaker-python-sdk#3397

*Testing done:*

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [x] I certify that the changes I am introducing will be backward compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [x] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [x] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have added unit and/or integration tests as appropriate to ensure backward compatibility of the changes
- [x] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [x] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by mufaddal-rohawala — COMMENTED** [review]
/bot run all

**Review by vikas0203 — COMMENTED** [review]
/bot run all

**Review by vikas0203 — COMMENTED** [review]
/bot run all

**Review by vikas0203 — APPROVED** [review]

**Review by vikas0203 — COMMENTED** [review]
/bot run all

**Review by vikas0203 — COMMENTED** [review]
/bot run all

**Review by vikas0203 — COMMENTED** [review]
/bot run all

**Review by vikas0203 — COMMENTED** [review]
/bot run all

**Review by vikas0203 — COMMENTED** [review]
/bot run all

**Review by vikas0203 — COMMENTED** [review]
/bot run unit-tests,slow-tests

**Review by vikas0203 — COMMENTED** [review]
/bot run all

**Review by vikas0203 — COMMENTED** [review]
/bot run unit-tests

**Review by mufaddal-rohawala — APPROVED** [review]

**Comment by mufaddal-rohawala** [comment]
@l3ku can you help rebase this PR with latest master and resolve conflicts?

**Comment by mufaddal-rohawala** [comment]
Closing this PR as it has not been updated for some time. The issue request will be kept open and will continue to track the fix here.

**Comment by l3ku** [comment]
I resolved the issue since it seems that this issue no longer exists due to a change in the AWS SageMaker APIs.

**Pull request closed without merging**
