### PR TITLE
Fix: Update Airflow prepare_framework Function to not use os.path.join

### PR DESCRIPTION
**Pull request by GroovyDan**
*Issue #, if available:*

*Description of changes:*
Using `os.path.join` in the prepare_framework function can cause an issue on windows. The `sagemaker_submit_directory` hyperparameter value gets incorrectly set with the current implementation. Since `key` should refer to an S3 key, we should be able to join on `/` instead. Specifically, this issue cropped up when I was using the `aws-step-functions-data-science-sdk-python` to orchestrate a training job. They are building out their training definition using the ariflow training configs which references this code. (See here: https://github.com/aws/aws-step-functions-data-science-sdk-python/blob/main/src/stepfunctions/steps/sagemaker.py#L111)

*Testing done:*

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [ ] I certify that the changes I am introducing will be backword compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [x] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [x] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added unit and/or integration tests as appropriate to ensure backward compatibility of the changes
- [ ] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [ ] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by vikas0203 — COMMENTED** [review]
/bot run all

**Review by vikas0203 — COMMENTED** [review]
/bot run all

**Comment by mufaddal-rohawala** [comment]
@GroovyDan apologies for late review on this PR, can you help rebase this PR with latest master?

**Comment by GroovyDan** [comment]
@mufaddal-rohawala looks like the issue this PR was fixing has already been fixed with the introduction of the `s3.s3_path_join` function. Closing this PR.

**Pull request closed without merging**
