### PR TITLE
fix: Simplify how we process test dependencies, which are supposed to include all extras.

### PR DESCRIPTION
**Pull request by ShailavTaneja**
_Issue #, if available:_

_Description of changes:_

Change: An alternative to adding extras to test requirements explicitly, all the time. 
- Test dependencise should not have to be duplicated from extras files to the test reqs file - which is error prone and can lead to asynch versions (depends on the developer remembering to update the requirement explicitly in multiple locations) 
- Test dependencies are a superset of all extras. 

_Testing done:_

pip install . 

## Merge Checklist
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General
* [x]  I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
* [x]  I certify that the changes I am introducing will be backward compatible, and I have discussed concerns about this, if any, with the Python SDK team
* [x]  I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
* [ ]  I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
* [x]  I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests
* [x]  I have added tests that prove my fix is effective or that my feature works (if appropriate)
* [ ]  I have added unit and/or integration tests as appropriate to ensure backward compatibility of the changes
* [ ]  I have checked that my tests are not configured for a specific region or account (if appropriate)
* [ ]  I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by samruds — APPROVED** [review]

**Review by benieric — COMMENTED** [review]
/bot run pr

**Comment by mufaddal-rohawala** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-pr
* Commit ID: cd9a03760b06f90feb6139a16791c319b99bb1de
* Result: FAILED
* [Build Logs](https://abkt2mlh3k.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=d123da01-c17f-45f2-98d8-c22e4f0d37ae%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Review by benieric — COMMENTED** [review]
Could you fix title to match format in [CONTRIBUTING.md ](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) 

1. Does this change how new test dependencies are added?
2. Where else are the dependencies that we are removing included? (ex, you are deleting `docker-py=5.0.2,<7.0.0` is this installed anywhere else?)

**Comment by ShailavTaneja** [comment]
> Could you fix title to match format in [CONTRIBUTING.md ](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md)
> 
> 1. Does this change how new test dependencies are added?
> 2. Where else are the dependencies that we are removing included? (ex, you are deleting `docker-py=5.0.2,<7.0.0` is this installed anywhere else?)
 Ref 1 - Have fixed the title and the commit message. 
 Ref 2 - Yes, these are already present in the respective "extras" files. For example docker-py=5.0.2,<7.0.0 is present in [local_requirements.txt](https://github.com/aws/sagemaker-python-sdk/blob/c8d1428b1176e020c5225161d0426d3dc8853289/requirements/extras/local_requirements.txt#L2). I validated that the ones I removed are already in one of the extras.

**Comment by benieric** [comment]
> > Could you fix title to match format in [CONTRIBUTING.md ](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md?rgh-link-date=2024-03-19T21%3A34%3A34Z)
> > 
> > 1. Does this change how new test dependencies are added?
> > 2. Where else are the dependencies that we are removing included? (ex, you are deleting `docker-py=5.0.2,<7.0.0` is this installed anywhere else?)
> 
> Have fixed the title and the commit message. Ref 1 - A new dependency will now only need to be added in the extra's requirement file if it's for an extra, instead of in 2 places. Ref 2 - Yes, these are already present in the respective "extras" files. For example docker-py=5.0.2,<7.0.0 is present in [local_requirements.txt](https://github.com/aws/sagemaker-python-sdk/blob/c8d1428b1176e020c5225161d0426d3dc8853289/requirements/extras/local_requirements.txt#L2). I validated that the ones I removed are already in one of the extras.



> > Could you fix title to match format in [CONTRIBUTING.md ](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md?rgh-link-date=2024-03-19T21%3A34%3A34Z)
> > 
> > 1. Does this change how new test dependencies are added?
> > 2. Where else are the dependencies that we are removing included? (ex, you are deleting `docker-py=5.0.2,<7.0.0` is this installed anywhere else?)
> 
> Have fixed the title and the commit message. Ref 1 - A new dependency will now only need to be added in the extra's requirement file if it's for an extra, instead of in 2 places. Ref 2 - Yes, these are already present in the respective "extras" files. For example docker-py=5.0.2,<7.0.0 is present in [local_requirements.txt](https://github.com/aws/sagemaker-python-sdk/blob/c8d1428b1176e020c5225161d0426d3dc8853289/requirements/extras/local_requirements.txt#L2). I validated that the ones I removed are already in one of the extras.

Got you makes sense, nice fix

**Review by benieric — APPROVED** [review]

**Review by benieric — COMMENTED** [review]
/bot run pr

**Comment by mufaddal-rohawala** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-pr
* Commit ID: 39dff719278d6e60a0cdf1377a67d8d938bb45d0
* Result: FAILED
* [Build Logs](https://abkt2mlh3k.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=402a4667-9bed-450b-8010-fd8baf602641%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Pull request merged**
