### PR TITLE
feature: feature store with_feature_group functionality changes

### PR DESCRIPTION
**Pull request by patrickmcarlos**
*Issue #, if available:*

*Description of changes:*
Adds three new parameters to the `with_feature_group` Feature Store `dataset_builder` class.

These three new parameters are:
```
        feature_name_in_target (str): A string representing the feature in the target feature group
            that will be compared to the target feature in the base feature group. If None is
            provided, the record identifier will be used in the join statement. (default: None).
        join_comparator (JoinComparatorEnum): A JoinComparatorEnum representing the comparator used
            when joining the target feature in the base feature group and the feature in the target
            feature group (default: None).
        join_type (JoinTypeEnum): A JoinTypeEnum representing the type of join between the base and
            target feature groups. (default: None).
```

`feature_name_in_target`
- Allows users to provide the feature name in the target feature group that will be used as a join key alongside the currently existing `target_feature_name_in_base` feature in the SQL JOIN statement. Before, only the record identifier feature in the target feature group could be used when creating the query.

`join_comparator`
- Allows user to provide a Join comparator, which will be used to compare the two join keys. For example, we can now join a row together if feature_1 (target_feature_name_in_base) in feature group `A` is greater than `feature_1` (feature_name_in_target). Before, only `=` (Equals) was able to be used.

`join_type`
- Allows user to provide a Join type, which will specify the type of Join in the SQL statement. Before, users could only specify an (INNER) JOIN.
- Enum keys are based on the join types available in the Athena docs https://docs.aws.amazon.com/athena/latest/ug/select.html

### Usage
Say we have two feature groups, `feature_group_a`, and `feature_group_b`.

`feature_group_a` has three features, `rec-id-a`, `event-time-id-a` and `feature-a`.
`feature_group_b` has three features, `rec-id-b`, `event-time-id-b` and `feature-b`.

A user may want to join `feature-a` from `feature_group_a` (base) and `feature-b` from `feature_group_b` (target). Furthermore, the user wants to perform a `RIGHT_JOIN` instead of a regular JOIN (inner) and use the `LESS_THAN` comparator instead of equals

Our code could look like this:

```
dataset_builder = feature_store.create_dataset(
    base=feature_group_a,
    output_path=f"s3://{s3_bucket_name}",
)

result_df, query = dataset_builder.with_feature_group(
    feature_group=feature_group_b,
    target_feature_name_in_base="feature-a",
    feature_name_in_target="feature-b"
    join_comparator=JoinComparatorEnum.LESS_THAN,
    join_type=JoinTypeEnum.RIGHT_JOIN).to_dataframe()
```

or without named arguments

```
result_df, query = dataset_builder.with_feature_group(
    feature_group_b,
    "feature-a",
    None,
    "feature-b"
    JoinComparatorEnum.LESS_THAN,
    JoinTypeEnum.RIGHT_JOIN).to_dataframe()
```

*Testing done:*
- Unit & integration test to ensure properties of dataset_builder class are correctly updated when the new parameters are used in `with_feature_group`
- Unit & integration test for the SQL query generated when using the `with_feature_group` with the new parameters.
- Currently existing unit tests are unchanged.

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [ ] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [ ] I certify that the changes I am introducing will be backward compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [ ] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [ ] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [ ] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added unit and/or integration tests as appropriate to ensure backward compatibility of the changes
- [ ] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [ ] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by trajanikant — COMMENTED** [review]
/bot run all

**Review by trajanikant — COMMENTED** [review]
/bot run all

**Comment by patrickmcarlos** [comment]
> * Build Logs

Looks the failing Feature Store related `sagemaker-python-sdk-pr` tests are due to hitting the max # of feature groups in the AWS account. This will require cleaning up these feature groups and rerunning the `sagemaker-python-sdk-pr` and `sagemaker-python-sdk-slow-tests`

**Review by trajanikant — COMMENTED** [review]
/bot run pr, slow-tests

**Review by trajanikant — COMMENTED** [review]
/bot run pr, slow-tests

**Review by trajanikant — COMMENTED** [review]
/bot run pr, slow-tests

**Pull request merged**
