### PR TITLE
fix: Add gpu capability to local

### PR DESCRIPTION
**Pull request by teticio**
*Issue #, if available:*

*Description of changes:*

Currently `local_gpu` gives an error of `Unknown runtime specified nvidia` when running `docker-compose`. This no longer works with docker-compose version 1.27.0+. Now the way to enable GPUs according to the `docker-compose` [documentation](https://docs.docker.com/compose/gpu-support/) is to add the following config to the `docker-compose.yml` file:

```
services:
    ...
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
```

*Testing done:*

Ran `tox tests/unit`

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [x] I certify that the changes I am introducing will be backword compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [ ] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [x] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added unit and/or integration tests as appropriate to ensure backward compatibility of the changes
- [ ] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [ ] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by teticio** [comment]
This change is necessary to support version v1.27.0+ of docker-compose
https://docs.docker.com/compose/gpu-support/

**Comment by teticio** [comment]
Yes, I was able to run inference on my GPU locally. Thanks for reviewing
this.

**Comment by teticio** [comment]
I expect this is pretty low priority but just wondering if it's likely to get reviewed any time soon or if I need to do anything else right now. Thanks.

**Comment by teticio** [comment]
Sorry to bug you @mufaddal-rohawala, but I was wondering if this might get reviewed sometime? Thanks

**Comment by navinsoni** [comment]
@teticio Thank you for submitting the change.

**Review by navinsoni — APPROVED** [review]

**Pull request merged**
