### PR TITLE
feature: TensorFlow 2.4 for Neo 

### PR DESCRIPTION
**Pull request by Qingzi-Lan**
*Issue #, if available:*

*Description of changes:*

*Testing done:*

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [ ] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [ ] I certify that the changes I am introducing will be backword compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [ ] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [ ] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [ ] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added unit and/or integration tests as appropriate to ensure backward compatibility of the changes
- [ ] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [ ] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by ahsan-z-khan — CHANGES_REQUESTED** [review]
unit tests failing. Can you check the logs? 
`ValueError: Unsupported neo-tensorflow version: None. You may need to upgrade your SDK version (pip install -U sagemaker) for newer neo-tensorflow versions. Supported neo-tensorflow version(s): 1.15.3, 2.4.2, 1.4.1, 1.5.0, 1.6.0, 1.7.0, 1.8.0, 1.9.0, 1.10.0, 1.11.0, 1.12.0, 1.13.0, 1.14.0, 2.4.2.`

**Comment by Qingzi-Lan** [comment]
> unit tests failing. Can you check the logs? `ValueError: Unsupported neo-tensorflow version: None. You may need to upgrade your SDK version (pip install -U sagemaker) for newer neo-tensorflow versions. Supported neo-tensorflow version(s): 1.15.3, 2.4.2, 1.4.1, 1.5.0, 1.6.0, 1.7.0, 1.8.0, 1.9.0, 1.10.0, 1.11.0, 1.12.0, 1.13.0, 1.14.0, 2.4.2.`

images just got fully released last week. can you check the PR again. Thanks

**Comment by Qingzi-Lan** [comment]
@ahsan-z-khan can you help me find the failed test case log?

**Comment by Qingzi-Lan** [comment]
@shreyapandit all tests passed this time. can you please review it.

**Comment by Qingzi-Lan** [comment]
> @Qingzi-Lan Can you please rebase this PR so that it has only your changes

@navinsoni, the change was pushed by @shreyapandit from dev branch. should I revert them back and only have my own change?

**Comment by shreyapandit** [comment]
Hi @Qingzi-Lan , I updated your branch with dev earlier. Since we have synced dev again with release commits from master, you would need to update your branch with dev again. You can do so by performing a rebase with dev. ie git rebase dev and with that you should be all set to go

**Comment by Qingzi-Lan** [comment]
> Hi @Qingzi-Lan , I updated your branch with dev earlier. Since we have synced dev again with release commits from master, you would need to update your branch with dev again. You can do so by performing a rebase with dev. ie git rebase dev and with that you should be all set to go

just rebased, want to double check, to contribute to SDK, should I start on master or dev branch?

**Comment by Qingzi-Lan** [comment]
@shreyapandit please review it again, all checks passes

**Comment by shreyapandit** [comment]
> > Hi @Qingzi-Lan , I updated your branch with dev earlier. Since we have synced dev again with release commits from master, you would need to update your branch with dev again. You can do so by performing a rebase with dev. ie git rebase dev and with that you should be all set to go
> 
> just rebased, want to double check, to contribute to SDK, should I start on master or dev branch?

You should start from dev, which I think you did. We just have a peculiar process where upon release there are some extra commits on master that made by CI that need to be brought back onto dev, which changes branch history and hence the rebase is needed again. We are working to simplify this  so that it won't be as involved in the future.

**Review by shreyapandit — APPROVED** [review]

**Review by navinsoni — APPROVED** [review]

**Pull request merged**
