### PR TITLE
[Feature - Hugging Face] Update Transformers 4.26 - PyTorch 1.13.1 Image uri

### PR DESCRIPTION
**Pull request by JingyaHuang**
* Issue #3669 

*Description of changes:*

Update Image URI for:
* Transformers 4.26 - PyTorch 1.13.1 Training DLC: https://github.com/aws/deep-learning-containers/pull/2678
* Transformers 4.26 - PyTorch 1.13.1 Inference DLC: https://github.com/aws/deep-learning-containers/pull/2679

*Testing done:*

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [x] I certify that the changes I am introducing will be backward compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [ ] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [ ] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [ ] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added unit and/or integration tests as appropriate to ensure backward compatibility of the changes
- [ ] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [ ] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by trajanikant — COMMENTED** [review]
/bot run all

**Review by tejaschumbalkar — APPROVED** [review]

**Comment by JingyaHuang** [comment]
Hi folks, I updated the python version as the log mentioned. But the CIs seems somehow stalled. Do you have any idea? Thx!

**Review by trajanikant — COMMENTED** [review]
/bot run all

**Review by trajanikant — COMMENTED** [review]
/bot run all

**Review by trajanikant — COMMENTED** [review]
/bot run all

**Review by trajanikant — COMMENTED** [review]
/bot run all

**Review by trajanikant — COMMENTED** [review]
/bot run pr, slow-tests

**Review by trajanikant — COMMENTED** [review]
/bot run all

**Comment by trajanikant** [comment]
Hi @JingyaHuang 
Can you resolve the conflicts and push back?

**Comment by JingyaHuang** [comment]
Hi @trajanikant, I just updated the branch. Feel free to ping me if any other conflict occurs.

(and sorry for the delay, I was on vacation last week

**Review by trajanikant — COMMENTED** [review]
/bot run all

**Pull request merged**
