### PR TITLE
feat: Add SageMaker Geospatial verison 1.x images

### PR DESCRIPTION
**Pull request by bgoginen**
*Issue #, if available:*

*Description of changes:*
* Adding the SageMaker Geospatial Images in us-west-2
*Testing done:*
 * Added Unit Tests and they are succeeded 
 * Ran all the unit tests using tox -e py310 -- -s -vv tests/unit
 

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [x] I certify that the changes I am introducing will be backward compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [ ] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [x] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have added unit and/or integration tests as appropriate to ensure backward compatibility of the changes
- [x] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [ ] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by benieric — COMMENTED** [review]
/bot run all

**Comment by benieric** [comment]
flake8 failing with formatting errors:

```
flake8 run-test: commands[1] | flake8
./tests/unit/sagemaker/image_uris/expected_uris.py:62:44: E231 missing whitespace after ','
./tests/unit/sagemaker/image_uris/test_sagemaker_geospatial.py:40:99: E251 unexpected spaces around keyword / parameter equals
./tests/unit/sagemaker/image_uris/test_sagemaker_geospatial.py:53:12: E251 unexpected spaces around keyword / parameter equals
ERROR: InvocationError for command /codebuild/output/src1034880947/src/github.com/aws/sagemaker-python-sdk/.tox/flake8/bin/flake8 (exited with code 1)
````

**Comment by bgoginen** [comment]
@benieric , I have pushed a new change to fix flake 8 issues .

**Review by benieric — COMMENTED** [review]
/bot run all

**Comment by benieric** [comment]
wait for team member approval before merge

**Review by benieric — DISMISSED** [review]

**Review by knikure — APPROVED** [review]

**Review by benieric — APPROVED** [review]

**Review by benieric — COMMENTED** [review]
/bot run all

**Comment by mufaddal-rohawala** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-local-mode-tests
* Commit ID: 1c4c5bbaaaf61b712fbddbfc013a802167523f09
* Result: FAILED
* [Build Logs](https://8huhkqo601.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=45cfbb88-5d2b-4faa-811f-81a0c3ad8c04%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by mufaddal-rohawala** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 1c4c5bbaaaf61b712fbddbfc013a802167523f09
* Result: SUCCEEDED
* [Build Logs](https://bkqkixfb59.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=5f9aa882-382b-4d5c-bfbe-3e51af79ff82%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by mufaddal-rohawala** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-unit-tests
* Commit ID: 1c4c5bbaaaf61b712fbddbfc013a802167523f09
* Result: SUCCEEDED
* [Build Logs](https://fegcnxu6da.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=e4aa6616-5dd3-4c97-abcd-8c0baa465f73%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by mufaddal-rohawala** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-slow-tests
* Commit ID: 1c4c5bbaaaf61b712fbddbfc013a802167523f09
* Result: SUCCEEDED
* [Build Logs](https://omfrydptb9.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=3b741a2a-e216-4d32-8d9d-f1a40d7dd9fa%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Review by benieric — COMMENTED** [review]
/bot run local-mode-tests

**Comment by mufaddal-rohawala** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-local-mode-tests
* Commit ID: 1c4c5bbaaaf61b712fbddbfc013a802167523f09
* Result: SUCCEEDED
* [Build Logs](https://8huhkqo601.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=c1e03736-5223-4c1f-bed7-39c95e5b3462%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Pull request merged**
