### PR TITLE
fix: Create workflow module scoped sagemaker_session to resolve test race condition

### PR DESCRIPTION
**Pull request by qidewenwhen**
*Issue #, if available:* 
Workflow integ tests (e.g. `test_model_registration_with_model_repack `) have race condition with model_builder tests. The latter[ changes the `sagemaker_session.settings._local_download_dir` when doing the `model_builder.build`](https://github.com/aws/sagemaker-python-sdk/blame/c8d1428b1176e020c5225161d0426d3dc8853289/src/sagemaker/serve/builder/model_builder.py#L610) and when the test is done, the tmp file in` _local_download_dir`  is cleaned up but the field is not reset, which blocks the workflow integ tests to upload model inference entry point file to S3. See the error thrown in 

https://github.com/aws/sagemaker-python-sdk/blame/c8d1428b1176e020c5225161d0426d3dc8853289/src/sagemaker/fw_utils.py#L453-L464

```
        if (
            settings is not None
            and settings.local_download_dir is not None
            and not (
                os.path.exists(settings.local_download_dir)
                and os.path.isdir(settings.local_download_dir)
            )
        ):
>           raise ValueError(
                "Inputted directory for storing newly generated temporary directory does "
                f"not exist: '{settings.local_download_dir}'"
            )
E           ValueError: Inputted directory for storing newly generated temporary directory does not exist: '/tmp/sagemaker/model-builder/40e2b7d2e61c11ee99ba0242ac110002'
```

*Description of changes:* Create a separate sagemaker_session in workflow scope

*Testing done:* Integ tests

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [x] I certify that the changes I am introducing will be backward compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [ ] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [ ] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added unit and/or integration tests as appropriate to ensure backward compatibility of the changes
- [x] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [ ] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by mufaddal-rohawala** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-pr
* Commit ID: 231215c141f332b52d46275b9a0020da0dbe4c06
* Result: FAILED
* [Build Logs](https://abkt2mlh3k.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=0b4776c5-0500-45a8-a878-6750a7d9d0f1%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by mufaddal-rohawala** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-pr
* Commit ID: 8ca69522c9736bfae52ea0b7ccaa8774fa5eb109
* Result: FAILED
* [Build Logs](https://abkt2mlh3k.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=158eb095-8b15-43a4-9910-b7ae4aa2c4a4%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by mufaddal-rohawala** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-pr
* Commit ID: 3704bddcaff43c77e493306c2cf81bbbecb54fd8
* Result: FAILED
* [Build Logs](https://abkt2mlh3k.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=0f3fa46c-f563-4993-b4c2-beb8fb8932c7%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by mufaddal-rohawala** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-pr
* Commit ID: 3dddbf469c7368031683a379a0853dfa9fb57e84
* Result: SUCCEEDED
* [Build Logs](https://abkt2mlh3k.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=7763ccda-0063-4aa0-8935-bedb612c50c9%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Review by benieric — APPROVED** [review]

**Pull request merged**
